---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.16.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    master:
      resources:
        requests:
          cpu: 20m
          memory: 150Mi
        limits:
          memory: 150Mi
    worker:
      config:
        core:
          sources: ["pci", "system", "usb"]
      resources:
        requests:
          cpu: 5m
          memory: 150Mi
        limits:
          memory: 150Mi
    gc:
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
        limits:
          memory: 1Gi
    prometheus:
      enable: true
