---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-navidrome
  namespace: navidrome
  annotations:
    volume.beta.kubernetes.io/storageClassName: "truenas-ssd-nfs"
spec:
  storageClassName: truenas-ssd-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
