---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-internal-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: internal
        url: "https://${GATUS_SUBDOMAIN:-${APP}}.${SECRET_DOMAIN}${GATUS_PATH:-/}"
        interval: 1m
        conditions:
          - "[STATUS] == ${GATUS_STATUS:-200}"
        alerts:
          - type: pushover
