apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
    namespace: security
# Create passbcrypt:
#   "https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)"
# or
#   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
stringData:
    server-toml: ENC[AES256_GCM,data:Y4bUxWsglmUuo4/qQpN6dDKd0d8D8sjY0ctg9Zu+wL0c/nlrUyce3wNTyyDW8kaNUSxoU7fUJT2NmoMANM5khSqBJ4M1N9xkOJpbaNoHCjRcY7Qj4a5IfBuUqPW2ZteB8O3fBtFXNCUaKNDj2nViH2dQr+DgrKdNDxJOXpW1XF4pA0VZ7CL2+zOfuJ7aDIzFrlSFxMFdMK0CbMYIpl9LM9QsBMfJUx2TRDxrLd+rDgfvGuQmxZLVghLeVTjGyNPxmjTiZDf8JwwHjL68E7CrE+1djmk=,iv:sGYc0ngfB86ewyW2Qf98Z7JILYZOQLcRvK3iVfD54vw=,tag:v3OYrC7k7dBguU71Qc9kww==,type:str]
    groups-toml: ENC[AES256_GCM,data:RtKo/H5NzgljlmfWR/hBYblMd8hclHULOSXNqU6ooitHwsoUzsWpmD7LapUNjncGe6PYKAbDSyyBkjiirNqZuZUhKqeWKkxLmkrEIQWdFOV4fLLq0MASDefNgC5/UayilpC2M4RS9CqZFXxTxciKEEs6h71dHL17D0UPg4pWUfwzrJzMghYJp5YWHX5U6HftJA==,iv:j2prl+vMUmoAAaPnY0/TIiS2X+s+Wx4WpLDnqMVa6Tk=,tag:RwSvbuomAUsgIdrBBEgjMg==,type:str]
    users-toml: ENC[AES256_GCM,data:tNHCL02Uf7t7JVw6zBrrkxmETNrov72IJluPL7x1xCyMt1byzXQS+op6+4jfQWfIOOFn0pabPTeVTc5k218l2sqddWXbIzN0np2FfqZ0h5UoDLV3VYfBZeWQbVOTBh+dvP6x8jNz5n4m6ruROxUc0j17ZWaE6fQChc7Dyl/PpjJVarNU1f2ZW4Jq76ZDg0Sh5MWnVoDyQYnHWHKZwv7juuoJ9D9HTvDxtKfZF7clBQVQ11DAafrFyAc+fMSn0hgsGwPSwKauSTeAqTHkLPG3XFRIfCyX87UK57Glvwvxp5b6v45+Itiko3vh57UEYvbZNhkiZRmkxAJdK4ixwIgBNrCA3TFKSkL6OOLoCM3KUQxNUJzJjDPeyn2XcEvyH+A/ZeJY2wqNsl7tRixCNqWvrV6x5N5e7QXv78he5Aux9LS5MTd6s6dVijZkmhNo/hUD957co8FnUKJivPG/161xhrCBvZEMJZrnRZpppSgbsGiZkc5MhHFwR7PaMPc+oMm6xuVQNGD+2CxpnrRI2uDAYSBDvZKhcgFp6TFI5McnLK2A+6c0STKTkseWZQa6YhkWgQc0WXGzo6sjp7ffebXy5D+bvnfHloedzIRI2CnOzTC/wDfdqUnZ1H18XREiZs3uga0kqBaxU7KFaIzsOocnOaecJCcBMyxs5vhYCrCG/kds+ah72YqtjjDdcq6wV0qb0JnBZwD8x4pvs/Xd/JAYimxh3uUu/cQHCb+ekxttH25vF48nsQ==,iv:TmpMgwlFhZMwbpuxp62mt7denmANRSbtN35Qu7Jy6dQ=,tag:pssiM+pSM3xLljKHRi32cA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ1IxY2ZTODlTdVhzekxZ
            elVYUTN3cUZRazZlVGlmL1JYK3BsdE1QeEQwCmdVVFZyNW5GTHBzZEtVdnhBOVdC
            V21YaEhjbk5INThMZEFvakhXc1dWdzQKLS0tIHZ6WmV2UUN5cHVicThEdi9nZENx
            bUxpdmtoSlBVOUl1RlBPSlJPcWRwZUUKf5h35miBWn3ZizPZ5hytAWBpCj7b4uOX
            +im5mhPgRqT4mmk6QGEVM6XhpDG/YBHJ6nE1+y7fpj3iTqOr4YhAgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T14:49:01Z"
    mac: ENC[AES256_GCM,data:/AFafGOasAt8YNOuqp40JXwpO0D/zoPJLuS8YoNTzHquvYT4fJGsTRR4V6kHW0lxZDY1SwgIpwPO3e3iBO8/XJI8P4ClY82j31BQYmeMzJVKRJr6xIZjzZ+JJNoJlHSEQLLMCy4MCIaSWASGrjtM/lUFeVOBhGYhgFLtZOIolis=,iv:55ojQjcA2ZOKO88n3hvFso9Ng6NChy0PEqVX3IiFRXg=,tag:MuH+TCgzWhK1saRnsCgi8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
