apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
    namespace: security
# Create passbcrypt:
#   "https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)"
# or
#   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
stringData:
    server.toml: ENC[AES256_GCM,data:0bykBVG89rJh+nFQbFMRP9FgiJh7NyAuyfgU5rlaJpHgFt4DY4TPWEPN0ZNE42CtmaYnaxEHGN0YzAsxGQyu6OFtbuhpLBnq4nv+dpHlcw1mynSsSsdcRSVrumzIF9HViF8EX7tHDLcHFYZqpTkfUO0Ns3YhIdTRge3mwJXdJCwqcXyF2YvaczAQDhMpwVApjgQRVCig9nqZQktIFuXXbYSq2vyaH8UQaZsA4+PE2iZj3AqsXSdkTSdsSxhkpcenAAoJuCd5yqDijtcsS6nCbrYvTj4=,iv:SPGAI7H9I9funE60DnAhy8zJsUWOrBIGxrLc+qDviNA=,tag:XqqYsycJLDh5M0MqxWc5RQ==,type:str]
    groups.toml: ENC[AES256_GCM,data:UnV2aHLUYBeeR0jccwpxBUCYmY27yeMW9RkezcFC5nkOpN7vtcsTCJYLtAoptNRGPmFKnbcge+2cD7YFG2BIRe8we+r1L8zSLl3Yn8ZNYUs1ei7zVJqaYHHReXDTfVZm+5EFw3GeaP9kKmJSBKvF3jr6UGCdS3E9X90k2kADnoWGyDtCckvyH7pGx0Er722rOw==,iv:4c1XMuQzZGOtFRqpY9wWhh6d/DYwRp3s2ih+n18f51s=,tag:SsbBXkRyzykwrefo/OUF6Q==,type:str]
    users.toml: ENC[AES256_GCM,data:ajXn6Rm2MwJAr4PUiSiwtpQGDigcUVGKTQHBiNJIV7EzvVJwWFt11oa50LO8eN9Ic6azvQybUCl79Ute3Xw7mL5e0j/MdYcVhulS0bdsQJXGXB7oWBc2/7h3U7/emsCrvqp6yyQgyU1jKbg7oa26fAZBArJrbMkDrd2ot/QNZExHdznw1k2bMrVb7qh4/5id8uW4k/fS38wBNFon8urxss1ABQG7S9IuAANTHhTFsg2tEPt/MOG7jsGxMe1jZPJRSiygO420rpk6GvgZ+eiUVEB/Km4BVdhoMYVch+uxGHITekL0P5+lj6DfIpNee3I7mqpzYPt36jif4Jh3nJ9jXef4B1WBlcRhJu0rhknRTYLUTzqDjJfs/1m1Y4/VHB3SHIQ8itqJRludbYFJrom9zkl4WwimqtT5LO3vtCDJuiw4HWPbb541YzoBiwtvXDZ34z+kFHxQohxNV2ap3lzCK67897mFXss4glcmFeCmpWUfUs0Q2FRAaGqiYghlgaoWWm25ry6ml7GCOB7q6RWZ5jQIHI2VmyCYoEvJSXnuAi+ofUL1jXqyq96gAB4Rvgkrebu/Xr72XCZh8nyccYyi0EKv6ncfpQhfmJKKMFCAfnZDiK4smgE9hXZZuQkCmMSOs/O8r8B4ZIlGVBSUNWajm25XUySFGb2d0jsaAQNUCNnjHAZYpO+Ag6wLHcJnQexhW5qfbIubrK3wS/NpW7UE80iGCfftkhaJGQ4Y5O3KKl+1yBRCQw==,iv:SDIgDeLlRwHaU8sAueqOsXT/Thdlw7J/GOE232m+Zho=,tag:9Rz4HbyIHwEJ/6E+cNQElA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mge8uraz65urs2222kpjqyfn6rkfgm90n7mqsd43dpclsc69nglqem4d5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NFJPOGpLeE1SdlBoWTZt
            d0E3aitYZUplMFgydjRORjNFaG5MbDBoK3p3CkpxaXpHOUxIVmxybDFGM0VVVFFI
            aFJqbVJiZEpFVllSTDFaR0h3V01UbTgKLS0tIEdXaHpZMy9zMmY5NDlvRHhuaC9w
            cDNOQWdHU2szMndGZUNtaERkdUg2Sk0KXsWZGh9HporaSWEroGkPtsjtIiRsoMDY
            W9ZCH+NBQ9PRWtrp8CKkEbn+YGuQQK2gSpIz0sEOQSfnxOzkqhkAJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T15:01:28Z"
    mac: ENC[AES256_GCM,data:JevhOQXZ4cZVwx8E67jUaoxugpBrd6oal52lHYbPR+YXMrBN1AzxXIv9S1iLnwBcU4Bo3wNVx20m/QVZ2zZ/cwddfUWbtdF15Gdpfuhf6IOi61V9Y5E4Ed9T3c3aQNGcR8Tq1pGGECzVby/GN6TqlQYhqKm01rpgrWMD3bHYm8Q=,iv:UZMelPQ0BD5kn0dLjURZjIS/6yswCpTgmeNaKE0oq1Y=,tag:OG3b7mCJL3OaNVk78ihNGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
