apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
    namespace: security
# Create passbcrypt:
#   "https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)"
# or
#   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
stringData:
    server.toml: ENC[AES256_GCM,data:jCMbimJTqe0pPMC9ieFR19zaIwEocu1/3dMipP95VzuoTXXHheowcxuToXe1xH9tUjT6Ks0fU3gcB9HiIoJDfXkiM+iH5eaV9RvfV5m9kzMwu/glZILakPiwnvZvS3d9Lkm5LfzRvTVEPCdbgq6lA4ijHQFw/unSlLyiB4hLV1fLw1wFkDqILIITwxe7TD4JCYam/7EPTH6h6Ef2cQGfurHNTnGLlXTNI6XT43MWH3+Yg0UvNXIIC+3av8ZMLSR41kfQxAwi3ZU+gG+mHjbwNLRGLj4=,iv:YW0VMvbk9fCO7OxpqFKnsoV2AXZmwWK9Fwsknw3MgFQ=,tag:r/mQyYUDX8sSBAyXCB7eWQ==,type:str]
    groups.toml: ENC[AES256_GCM,data:HY71Ez1cqkb/hSizXWsJt50FVqH9BSWeNnYboZhcEKDmmVi+vNlq8NIAj2s5uK0i6iTAHlakjKa7tA+Z2QRZqNo0oLVpNE8D1+lb4ZgljjadFIJ2swTylaIAs6vNAxz5RDzpgGPY9QPljLGXzIWGMbW9EeL0EMJV8Qwm1CUMpSaPZb8aPxKFNPPgxmso4BxHag==,iv:kqHX3Zvz5mgiFDWFbkcmr5fpKzadVGga5Qv2sSTl+vA=,tag:BqAEyFLrlenXk7LkzaiSxw==,type:str]
    users.toml: ENC[AES256_GCM,data:pByYxhyMcj04g5cXqXJsWH43eSlO6yZN0Yn9ImDfpfoe4BaLxtbalQznBs3Dlhx0oF1xZwkW4uYmrFVx1MMCeRPaxjq7HS4WSyv+uh2kxFgc3mTTKKrirXXcG+cZPWx+jXYEUMf/lbNxsapkc4bowLDR53Mu3VLuzder3OpvSR1k7pNHcQ8nKDCyoY9db+/7HTPkITfv4E12CgsUSsE0n0AqUSSn6Ijfh4XEZZt7mWajNjLvwmf4zGmMYgG0DJ+5Mi8Ik9d7ps0htiv1O+x7+d/RyYfC/YzhMPW0+QV77YVPE5rfGB0WUWaXhEbqhDHBTIcRCyiog/pRrNLXvKXhdj0qXZNP472KaC6x3wltWifND2N2lwmwUQzYvY6b0az9RJ3RqTM5q9EtLrmd/IRrfCRtK5B0g/VYyb0rbXYBYWAjnL52neEpngZ095phN9lBPFvTTWfjJ12lz22NKdbfazoNozgk3aUv+1CvtTrW3LRABfydaXFhF8HER0UF4JTnYnAZxb18kaWuKGBTfb1u0LjJlvKPu9Z54GKabvQDheDs5w8sDQsDlpAJzSl2uoL2oh2qr7RLDGakNp3W6dVj+sSmE1300f89yO0hnbNQzrE9Yh6Su+nYkEWLz77GT9C4Nf8wxHHnYgVdtQccNhQBuWgAeAY2Ukn/Q9jFXa1xLbpxZGSU/qNiCTDSnM1q6N0J48TfSBiNDo/5b0HQt00/yTh61m0F/v3kNUZxgjPz+GrEzLtbPg==,iv:BBsskk66lgvFW1eJFT/AzLrZKTXI1aw+QUwPpsgibJc=,tag:KsLTo5/DmA0m2/hZroN+JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ1IxY2ZTODlTdVhzekxZ
            elVYUTN3cUZRazZlVGlmL1JYK3BsdE1QeEQwCmdVVFZyNW5GTHBzZEtVdnhBOVdC
            V21YaEhjbk5INThMZEFvakhXc1dWdzQKLS0tIHZ6WmV2UUN5cHVicThEdi9nZENx
            bUxpdmtoSlBVOUl1RlBPSlJPcWRwZUUKf5h35miBWn3ZizPZ5hytAWBpCj7b4uOX
            +im5mhPgRqT4mmk6QGEVM6XhpDG/YBHJ6nE1+y7fpj3iTqOr4YhAgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T14:51:32Z"
    mac: ENC[AES256_GCM,data:jxEk5vuu7Db+XmKyd2e1iAGvCGYi6YNuFGbAzp/4gWp5VZgpFn6yudbwjHXbrO9PLTbzsp1V4CNHJdNU+4INpwQXw6jyAAaRj2EFKlmijtZbdh9g3Ktqg486oYGDg/a3D5Zy/TDvcNtkgccQHCvsFSBGYwje5gFhNNV1ww630J4=,iv:W8ib6kDfRJPaT2aX2E3zuNtPEH21/c94h2u/5XYn/Zk=,tag:Rzk/Ky5SG4llb8X9A7bTdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
