apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: observability
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:A8wNgVC/fVG7o6uWJPS621rFMFf5icjluINk9hG3,iv:+1q3+lin3Lfn9wduuejfEE09SNo2eDhfwj2kLigWq1o=,tag:GIcZ4/3DAJjjgx7yw73Myw==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:lTQwNTIuvr8t8PYiKYX9zeAJPjpLA8Y9qtvfI6Hq,iv:Ag2XZkwRzocvm0mugm92yEmFViHeUPDvd3e4+HByKpo=,tag:Ek/V90001uVCQURFeePHMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUldWY3lwdEhURUVJRE5B
            V1M3Wi9WNG0zYmJLYmZVVFE2NGxCalBkZ0JvClo5WTBYdUhnaG9RSFlFNjJXaGxx
            NUN5eWxWRzZFMUNTSTduUTJPa0xKeWcKLS0tIGl4K0UxMHNYTEs0MGV5RnRmb3Zq
            b09GeDdNRDB4RnN2WkhwUytFWE02S2sKr/ioDNQ7UPj10M5DMu32Uq/4aqJvH3mX
            k7sMTMDF7pC35v5bm7AFOArRp0YOlCIJIXwJEtMkYP6csTlDmu9xEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T23:00:38Z"
    mac: ENC[AES256_GCM,data:Yfl0APfhxlrXn5cjacY47CRwO09WnTFywcGntBYXGlqsRz1mKXN9TRar1VC7G8zZpB+1F4KDfr0FJIxpw63yd5rojW/djNUrXecfPNX27Vnq1PDgU3EDBaNorLUKly33amd7nyDCPDfIlP7470YjHFtVZHdzZWZ7shXIvfnDxM0=,iv:nUcdvMmungvI0apg0xQRU/av4aktZmkVuOwYZjI9cZo=,tag:ZJUtmwezIcxS2+g6cxbQXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
