---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanager-secret.sops.yaml
  - ./helmrelease.yaml
  - ./prometheusrules
  - ./scrapeconfigs
secretGenerator:
  - name: alertmanager-config
    files:
      - alertmanager.yaml=./config/alertmanager-config.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics.yaml=./config/kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: observability
generatorOptions:
  disableNameSuffixHash: true
