apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: storage
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:7EeZn9A=,iv:Y2fOnjolaf4Eh8q2OTCjR0ds9cgmvw/HfISypnJM//w=,tag:vo7Bu3B8P8wIpiHSSQk3qA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:AvoJjnql++zGSmN+DPFkMaMs5RvMHeL1XFztvA==,iv:WcFwCdsJjiVW/h5kFyUuoazDFC4pnhqwcEKVaK2aP9w=,tag:DPh1kn2PJWfToaZjtNCuew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveDBpM3BZTG14WG93N0py
            UFhHMFRQV21IRlpOV0MreXBVZjZlMTQyMXljCnRaY0REL1BlZWg5RHJMeEVIQkho
            L1pQLzM4Q0VpVkR0RTJFcHhWRHhEQkUKLS0tIDN1WUV0KzhpMDhDZ0hMdnRzU1FE
            MjFsWUN3V3dzUDNEVSt3dVZTczByM0EK6cFQPXXPrjiNT0U0392r7BCbKpZ5JtP7
            XJuCQpoLQ7voqHv34m2Nwe1o8EBkhPelqQpBUiffNniYRqoT2W6tSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T15:22:04Z"
    mac: ENC[AES256_GCM,data:C44HW24DlitJqbfz0qXfjv483XyFhLgfDkNOnYgpGi1Vrh0ii/6s8C2I2wu2FH/xcG87QyzYTFgPNhr0EHo3vaxKFlv7IQ/n2SRoFiN9YmyZ5BfpJ9C3pwEj+21Yncd3PlPmZsXTOTVPm+RnJVxB6V8S55AlvazxmN7vhg6f9Os=,iv:EgrgXzEG8+VtbxwhhJtUGCqvwUhvOsq9FN17tg83yMk=,tag:L7mXq77rI+hFow0FcUSJOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
