---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: storage
  annotations:
    volume.beta.kubernetes.io/storageClassName: "truenas-ssd-nfs"
spec:
  storageClassName: truenas-ssd-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

