---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_CLAIM:-${APP}}
  namespace: ${NAMESPACE:-default}
  annotations:
    volume.beta.kubernetes.io/storageClassName: "truenas-ssd-nfs"
spec:
  storageClassName: truenas-ssd-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${PVC_CAPACITY:-1Gi}
