apiVersion: v1
kind: Secret
metadata:
    name: portainer-secret
    namespace: portainer
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:so/3lfGLW0Q++Uau,iv:V6kqT/UlNa716wtH0GumUtQ0AN1U0Kj2U0ujqzlNLjY=,tag:lDdawbavQfk0NQ12YFyj+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR084MVp1K2grTEVyQ1N0
            WGZhUlNyM1J5dlEwajVvUFA2aG1VYkhvWHdNCnZqS05YcHdBUmhXYzI1RUludGZC
            S0JuZkVlZTJzUmhpY09ZblQzVFFxUVUKLS0tIG14YTFPZlk1MFlCWDQ1ZEdRNXBi
            d0dPREt4NEduaCtRamxYMy9zVXl1UTAKN8sfV1axu3mGUZKZr+facILqkvdoua1V
            fTk6g5UOXS+2LwxS3iTISowPDWu3ln3Kdrt/mlsduAijecdMVyA5wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T08:11:13Z"
    mac: ENC[AES256_GCM,data:bgspKDL4H6YTOjjlf8x75BHiuM+Nhnv1dOQTL+53SwGvAguEdQUGlEDivrgZfqm1JGrqIwIoaG2VLsW5qewc5Gl+fe0CrKA2Y7B/VzLtX7v4jwGluiYrS4IPPVP2dSHHf2k+7q2E/q3iiP49FHl/YGC68rteRQKWTQysMniVhDE=,iv:fD9ihXi6NPFKfwUD/E1m03HgBOx+cPpG7+xqmCb6WGo=,tag:B7e44zy5PIEm7o8xfUhV8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
