---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-pvc
  namespace: portainer
  annotations:
    volume.beta.kubernetes.io/storageClassName: "truenas-ssd-iscsi"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-ssd-iscsi
  resources:
    requests:
      storage: 1Gi
