apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:9JEHiO3SD9WslhCwlgiyqSnMkGwJyexklq9MqzvOFsKRETFW,iv:3SqVfmLpvjtYue8vhztGvtgKGkF5b+lpyAauenWLXJg=,tag:GSZ5Y384xQ/PoZrzEynUWw==,type:str]
    credentials.json: ENC[AES256_GCM,data:EnUH3DW8vHN6y58718iMAD6xV4/XHoSli6aua62PM5UvCiy/dZVYJNpPYMVrqoNWNEIbR9Mz0W1ski1DknMH00yc2091+2URJGzX/clBWLncZxLQCKD9KlC0qlhglbdLz/m5d7CzpTWOGsGWhPJ/CrTjixvr+UBf3c+MHTDP9+hsLqvcf5F6E9ZfGy5wWbHhawX0+mK2kwJlUKytzFig6iCkQW8gudJzS3OpJZ6bDQ==,iv:DdsjI3Vz78eYI0vAKRWO9JvBMmBVPWOU00g7lmNIvaQ=,tag:8K3Xc5kylSdzX4uxm7owBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcTloRThQQk40NHRaRmc5
            ajNtdmI3RzJ5TWJEa05SRFcybU82Qm9EWVdvCnlFMVZTU1BQdXY0ZzBRMDN2OUhT
            N29CTzFiNUxrREJDY0FEdzk2Zno1YlEKLS0tIFk1SlRveVMwQXNPVldrUUYxdjJh
            QkdSaWMxbktvODk1MFIwMnVlVUtIRDQK18twwbug6tHGakqgsHNjXcqz9NCGCQmq
            KW0PhpNtChELz7BbTksq222TmWx7CEIh1ZI32SDr+HgHvJg70Sclxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T11:53:42Z"
    mac: ENC[AES256_GCM,data:g7297omSOG4CWFIC+EC1IUee7SbT0VSGqH8+7LswFG8TGhIKjR1CaB2YrHWkfM1LW2+I3mNRXY57+nssZSnTBVF4aIFE0W347PlcEcqazQ7Wn4fKgg0AH9ltRblxqwsOa8D1SN9XC81g8QKREgFNI2ijID2tiwJQsGvJiIf9muA=,iv:sUu7MPC00DLjx87s6Xc8ET/udTl2gg3E1fEb7x40FhY=,tag:lIKhziXNkX9Mz9yjbBX8eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
