{
 "title": "Cert Manager",
 "tags": [
  "cert-manager",
  "infra"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status{ }, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Certificates Ready",
   "type": "stat",
   "description": "The number of certificates in the ready state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition) (certmanager_certificate_ready_status{ })",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Earliest Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(certmanager_certificate_expiration_timestamp_seconds{ } > 0) - time()"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "description": "Status of the certificates. Values are True, False or Unknown.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(avg by (name, namespace, condition, exported_namespace) (certmanager_certificate_ready_status{ } == 1), \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(avg by (name, namespace, exported_namespace) (certmanager_certificate_expiration_timestamp_seconds{ }) * 1000, \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    }
   ]
  },
  {
   "title": "Controller Sync Requests/sec",
   "type": "graph",
   "description": "The rate of controller sync requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(certmanager_controller_sync_call_count{ }[$__rate_interval ])\n)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "ACME HTTP Requests/sec",
   "type": "graph",
   "description": "Rate of requests to ACME provider.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path, status) (\n  rate(certmanager_http_acme_client_request_count{ }[$__rate_interval ])\n)",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "ACME HTTP Request avg duration",
   "type": "graph",
   "description": "Average duration of requests to ACME provider. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path, status) (rate(certmanager_http_acme_client_request_duration_seconds_sum{ }[$__rate_interval ]))\n/\nsum by (method, path, status) (rate(certmanager_http_acme_client_request_duration_seconds_count{ }[$__rate_interval ]))",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU Usage and limits, as percent of a vCPU core. ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (rate(container_cpu_usage_seconds_total{container=\"cert-manager-cainjector\" }[$__rate_interval ]))",
     "legendFormat": "CPU {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "graph",
   "description": "Percent of the time that the CPU is being throttled. Higher is badderer. ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (\n  rate(container_cpu_cfs_throttled_periods_total{container=\"cert-manager\" }[$__rate_interval ])\n  /\n  rate(container_cpu_cfs_periods_total{container=\"cert-manager\" }[$__rate_interval ])\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory utilisation and limits.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (container_memory_usage_bytes{container=\"cert-manager-cainjector\" })",
     "legendFormat": "Memory {{pod}}"
    },
    {
     "expr": "avg by (pod) (kube_pod_container_resource_limits_memory_bytes{container=\"cert-manager-controller\" })",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "avg by (pod) (kube_pod_container_resource_requests_memory_bytes{container=\"cert-manager-webhook\" })",
     "legendFormat": "Request {{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "description": "Network ingress/egress.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(\n  sum without (interface) (\n    rate(container_network_receive_bytes_total{namespace=\"cert-manager\" }[$__rate_interval ])\n  )\n)",
     "legendFormat": "receive"
    },
    {
     "expr": "avg(\n  sum without (interface) (\n    rate(container_network_transmit_bytes_total{namespace=\"cert-manager\" }[$__rate_interval ])\n  )\n)",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}