---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
  annotations:
    volume.beta.kubernetes.io/storageClassName: "truenas-ssd-iscsi"
spec:
  storageClassName: truenas-ssd-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
