apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: security
stringData:
    AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ENC[AES256_GCM,data:pvIrL0XhCy2QMvjxWIjnI1dL73I/tlOHvSSsxvzf1oA=,iv:933Tu7mdw/kDfUHiC7XTXdSv3bVjZLRMXiKmPNqSB1U=,tag:6c9gc/9DErYMeuk0X6MPiA==,type:str]
    #ENC[AES256_GCM,data:RqGOrj+RdGNKZTrnHQKlto8Jm7ypetu+Ixrq1YxzyxzzdtAh5Foxyd1Gog8mu90NkcuTTDVv4SkWwueAKMU5D6GRpJFs8hTvvfo=,iv:j0vjRJsSbaohoim8xouwOWEnQFmeCr8qwxzkgmPGKMU=,tag:kRmkYHunmSxZPLc5+Rskog==,type:comment]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:ldHxC76F5v+qKMxoMggQttoAu6nDDW1kJbMNdB8PVE0iUIY46VYeSnh8moMdu/fTk6ZOfXa0wQ2/Nevl2gg7qw==,iv:m6lAxQ3yWN1mq7XON/rjqXI3YVExvqc1phOvzss7pvQ=,tag:cXyUWjwd8yqtVvJRkv0e8w==,type:str]
    #ENC[AES256_GCM,data:RqGOrj+RdGNKZTrnHQKlto8Jm7ypetu+Ixrq1YxzyxzzdtAh5Foxyd1Gog8mu90NkcuTTDVv4SkWwueAKMU5D6GRpJFs8hTvvfo=,iv:j0vjRJsSbaohoim8xouwOWEnQFmeCr8qwxzkgmPGKMU=,tag:kRmkYHunmSxZPLc5+Rskog==,type:comment]
    AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:jeCS3FvtyCoQuVH3Oi9BkQv4DHtcYe3J4AXb2YaDSO3GXsSeiX9+zjntjntFURn7cvuXQG96C5L7wfszKzrZVQ==,iv:mYXNqpoaQ+wcHCBMHHo7U4xfVOvK7y1KvXzWk9LnFmE=,tag:V6eYz407hAteYEhmvFUSjA==,type:str]
    #ENC[AES256_GCM,data:RqGOrj+RdGNKZTrnHQKlto8Jm7ypetu+Ixrq1YxzyxzzdtAh5Foxyd1Gog8mu90NkcuTTDVv4SkWwueAKMU5D6GRpJFs8hTvvfo=,iv:j0vjRJsSbaohoim8xouwOWEnQFmeCr8qwxzkgmPGKMU=,tag:kRmkYHunmSxZPLc5+Rskog==,type:comment]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:RClGiDub04NmbNYzx+4GSFcTXYW3hW2gNcWiSw5IP+ZboQ1IhJ32nCTV3tjim8EF++swS8X3W1ln0ddSMmVmdw==,iv:FyVK2SZ5HQd4K0zXdn6/Kv31apNK7OOWi0o8uNi3Emo=,tag:GCR9IX0nb0QjQXfoNLbiKA==,type:str]
    #ENC[AES256_GCM,data:RqGOrj+RdGNKZTrnHQKlto8Jm7ypetu+Ixrq1YxzyxzzdtAh5Foxyd1Gog8mu90NkcuTTDVv4SkWwueAKMU5D6GRpJFs8hTvvfo=,iv:j0vjRJsSbaohoim8xouwOWEnQFmeCr8qwxzkgmPGKMU=,tag:kRmkYHunmSxZPLc5+Rskog==,type:comment]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:4MXhWAIB9hsXD1MNgGunzgcQRDMzcXE01SL1rhlzaDZNPNSAhMfJ1KWhXYny7oMrji0apSrEUPPDZmIZenje4w==,iv:twOchNVxyjD2wRjGHabZFAqrtTJoWZyyj0s4Lom1qPc=,tag:+5Yho8Ih2hAFP/HSuo0rOg==,type:str]
    AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:b392WBhG84g=,iv:UO2vsErwGzaN81Q/bRVjZGPy+2lVyNQZqC7a/Tmxc+8=,tag:e0+Ja7rPcA9ZZu0pTBoIrQ==,type:str]
    AUTHELIA_STORAGE_POSTGRES_ADDRESS: ENC[AES256_GCM,data:IHl/8+RmSb0xxXlIyZBaoqVCZc7CXaZo0MyUVH2pHYiPVls3aYI2yA==,iv:GZZTMFv5tm+4FdSTHGVwonaFOoTaUAqzJCK++7/nAkM=,tag:DkstfpA9zRfxxl4PY5iqYA==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:I/dHDzvIXbA=,iv:JUV9hx+Nn9y3iqLyLOAEOOlyQiZH17KvObwMnARdTUQ=,tag:IP4+bm6SGDVB4idBZt0Btg==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:sTMjW3eEVl5EiM+9D/BO4r8sJoqF/1lDePsolun325Q=,iv:F7j98dKp9flcdfi7KXT7eA+TYHclzECEvIeKTzUBjAE=,tag:3jbAdoZQiuiA/4/V2XI9vw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:iidjMI51lsg=,iv:ZeFWmmXu+u6BLiDAG165TjrPSqFcQsvzldfPsSEAWhc=,tag:RC9EVA1FWBy//j/QpKyXrA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:CfxoCFnTrcAPl4JH6K9sglOe9ycfI8XXl0c2RP8J28UrdEE9VJXRTQ==,iv:ZTlRMuYVS/bhebcuP4DjD3YjdgsUbNHy90mMFtIzJi4=,tag:ithLBxJl5BRYapGOoP6TOg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:4OdP/FkMrWU=,iv:CsEO23JGeY8PoOGlodjzqR6VjwD8NTT+4tqsMqsPyaE=,tag:TwYpdgF+4tQfbY8s+ly1mg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:0CBV2FyafifRnOUB4IOTm6VtYiskj2jy2spkvxB5FbQ=,iv:cbXGNR1pPQXWvZTqHxsRyd0D9fHtbGRf+XfG8EBj/ZE=,tag:sranHnxtdD9UGu2ctNYVVQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:yYhCXGHEFmQDcG0DlL0IiG97nSk+V2Vl+3SJfC/NHNk=,iv:XOSXEm9jyh0VzuFI+jyvyw9aQiLJgmPhB7YZ7vbmjrk=,tag:lKEzBCI43hk/qbtuBfhtFw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:EO0kdXZKDYCnXHV4/g27rIK3xqqf,iv:uUAUOvUdL2merESGynWp33gnQvQxZ7dqdI8wDO/iqdA=,tag:2i3HAVv7/CPte6PGimoBMg==,type:str]
    SMPT_PASSWORD: ENC[AES256_GCM,data:1mxjUjdrlFtWhVZrtvpEQvJB56JbYcZjE7rzHXVD/j1sVd9XvCJMxv+IhXaQNwmCUL4=,iv:UAoQqB+SXg9syhtPmocvSZJmVJQTyS/e2756P2Efln0=,tag:vk6/2esXvjfasNIHxmTz/Q==,type:str]
    SMTP_ADDRESS: ENC[AES256_GCM,data:DRApDbIKlfduuzidKJ7GzkH4SRVMyds=,iv:VFFKvJYYErQRjhYJOVT4yKFMftF28aZ4y0WoJW+gnT8=,tag:XR4WJxSWykqJxLXa7lijkw==,type:str]
    #ENC[AES256_GCM,data:RqGOrj+RdGNKZTrnHQKlto8Jm7ypetu+Ixrq1YxzyxzzdtAh5Foxyd1Gog8mu90NkcuTTDVv4SkWwueAKMU5D6GRpJFs8hTvvfo=,iv:j0vjRJsSbaohoim8xouwOWEnQFmeCr8qwxzkgmPGKMU=,tag:kRmkYHunmSxZPLc5+Rskog==,type:comment]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Pb/VJb8SPh77YYh5eSiZSnbgpSGUDj+VDfqcQ88hQGu5wku+aAS7HRGfcQQ7k6EkIWFYXoE4i6MXsfC4BznIBg==,iv:0gMQI69JoyznYS0w1hWYF8d1XnLSpsqYLtd6T4WHtS0=,tag:qU8blbBzfH0p8ClPjAF8nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGdvZlR6OHZOQlJKd3dk
            L3lWaFdicCsvUUdNSHdkOWFVdW53T2J0VUN3CnBKTlFyWHkzSUhrRUwzT0g3MTJk
            L210ZGFHbm9BNld6amRWV3E2UnJaQWMKLS0tIGhRQ01scFRqUGZLQnZydHJDTUo2
            eHlEaCtqcWZpQWE2TlRrQzViN3l3a2MK9sUZenSbUifmxoC8ocjzxh73rwJ3cE2R
            rjV04zLdpkwsfaEcKhqWNqnmZ1lh4b+maCllGzUSNAgs9k2WtQYhOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T17:40:26Z"
    mac: ENC[AES256_GCM,data:oBm6tl9lJRfg4KXX3L1JNGC36THDavl2qjxnqVvparJxyt42F+ph8LtnV/umIykegZdtWnBgop6T5WV8nln2GMPrGQ2Q6IjV/NZnOY3Zugws2n/6EvL1GRbfyASUXJhgtvRLtvMWmhsbkJW9Lb3nnDB1GjXirmKv8Z2dxUJAKmk=,iv:OZIaPVBY9f+oW6zscROZls+hlWOEMQUNH9r183lN7XY=,tag:JnTXc8gQso+KPBDxbDXANQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
