---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authelia-oidc-jwks-key.sops.yaml
  - ./authelia-secret.sops.yaml
  - ./helmrelease.yaml
  - ../../../../templates/gatus/internal
configMapGenerator:
  - name: authelia-config
    files:
      - configuration.yaml=./resources/authelia-config.yaml
generatorOptions:
  disableNameSuffixHash: true
