---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          qbittorrent:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.5@sha256:c019af23966ebafcaf1713d4553bc043246858b711a7d57d8bee358a89990a3e
            env:
              TZ: ${TIMEZONE}
              QBITTORRENT__PORT: &port 80
              QBITTORRENT__BT_PORT: &bittorrentPort 60112
              QBT_Application__MemoryWorkingSetLimit: 10000
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                192.168.20.0/24
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_Preferences__WebUI__AlternativeUIEnabled: true
              QBT_Preferences__WebUI__RootFolder: /addons/VueTorrent
              QBT_BitTorrent__Session__AlternativeGlobalDLSpeedLimit: 7812
              QBT_BitTorrent__Session__AlternativeGlobalUPSpeedLimit: 1171
              QBT_BitTorrent__Session__BTProtocol: TCP
              QBT_BitTorrent__Session__BandwidthSchedulerEnabled: true
              QBT_BitTorrent__Session__DefaultSavePath: /data/Downloads/Torrents
              QBT_BitTorrent__Session__DisableAutoTMMByDefault: false
              QBT_BitTorrent__Session__DisableAutoTMMTriggers__CategorySavePathChanged: false
              QBT_BitTorrent__Session__DisableAutoTMMTriggers__DefaultSavePathChanged: false
              QBT_BitTorrent__Session__FinishedTorrentExportDirectory: /config/qBittorrent/torrent_files
              QBT_BitTorrent__Session__GlobalDLSpeedLimit: 0
              QBT_BitTorrent__Session__GlobalMaxRatio: 10
              QBT_BitTorrent__Session__GlobalUPSpeedLimit: 0
              QBT_BitTorrent__Session__Interface: eth0
              QBT_BitTorrent__Session__InterfaceAddress:
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              QBT_BitTorrent__Session__InterfaceName: eth0
              QBT_BitTorrent__Session__MaxActiveDownloads: 100
              QBT_BitTorrent__Session__MaxActiveTorrents: 200
              QBT_BitTorrent__Session__MaxActiveUploads: 200
              QBT_BitTorrent__Session__MaxConnections: -1
              QBT_BitTorrent__Session__MaxConnectionsPerTorrent: -1
              # QBT_BitTorrent__Session__UseAlternativeGlobalSpeedLimit: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
          vuetorrent:
            dependsOn: qbittorrent
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.2.3
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/addons
            resources:
              requests:
                cpu: 10m
                memory: 25Mi
              limits:
                memory: 50Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 4000
        fsGroup: 4000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_IP_QBITTORRENT}
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *bittorrentPort
            protocol: TCP
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: &host qbit-k3s.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: config-qbittorrent
      addons:
        type: emptyDir
        globalMounts:
          - path: /addons
      media:
        type: nfs
        server: ${TRUENAS_IP}
        path: ${NFS_PATH_MEDIA}
        globalMounts:
          - path: /data

