apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: media
stringData:
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:FeOQX5M/XwA6JBn1,iv:NwDQo33/nM/0zN1sGgx4gts8a4RgvHhM24af8xbULM0=,tag:c4uiMIp1RaW4iyLG12qTSA==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:3TtAQA==,iv:VUTuzK6C+HFfl7OyWEs38UgHwTfEBZHGv6E0fadYv1Y=,tag:IqPvoVPqTvKnDSYCCJGscQ==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:hm+N9+9JgQg6V9nvJPquCfNQFN4Te5pL3idODRjOHTPUb3UkKtYgcAIYmfA=,iv:uj6p85fRluqUJuTMC+h/q2+VI5ozX3132Qe6n1L9ewM=,tag:lV+eIvGIaNR+woJDLYBM4Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:+aolU1u8U55xBe+RBsvYcDyt/H1SmH1Cj5hjk6tfUDHDbUphlX8p2AfSgts=,iv:0v4eEUHtHzkrU9VUd49UWGw51iiwq779lW+69ql0HKg=,tag:ftrsmMVYVse8A1FDlfv1mw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:ha3u6a/BLtbuPaAsUX9xfZ0=,iv:hovTeBntFjULXAm+BG3zR82l95UcGvoYqLHWVZfiMLk=,tag:3zG1+lcT2gRLhLih9pzM3A==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:f3Uw4bHdnMjvybVh9hXE4rC0cT2926IDIkZH,iv:gWngUd0SH7cASjKGFxTnZ+4tu5Yt+qwOpilMMqYF1sU=,tag:uSFayqP65t0CIsZV9EUedw==,type:str]
    WIREGUARD_ALLOWED_IPS: ENC[AES256_GCM,data:J2U/fb2gw10x,iv:gzMqB+HuSjHKsGjUiEq/hlZQDP3bN97AvWuFjJmeoCU=,tag:plqEjD/OFjb/Sn/fPAxmYQ==,type:str]
    categories.json: ENC[AES256_GCM,data:eYP7Doak49urkRsqPOKY5sgxjv0vgV0TZLN7ORIr37/pfzcBrHFeqbtexC6XPdjXUEaARNjECxpAf3iblC/2CtGzjAtgugyo81Es39qGdFeyzdteUIVpGbwwsrTIRKcW5YKaF2UdKuxf4ultJbVGrU5fmWJZQErshNt0Zgig7CmBTaKtFgIH5IzbSa7EWH4Q20d6QgKJ7xYBLRjBy6fuC9hTN+YYy8M0yfU9IxpCS+nIRQqZ+bAt/k+Qk11KosKxmnY5jwspkxWbjaJUwgScHpyxZEyY5rCDF/FfZhsdfavXAjW+fIfzDi4mv9qwPmT2ob1YGtqmKdNwpY6lwG7OYy3el4P8QyqJGiIf5lhTjK4dUhelNIopItgBr2sSzVyNTQwjR6Trkub6EXEOmc12Triw5r//qRXKO7KSM91z5cv3P4zA/sHWvDW7mvcL96ehotBFFXau+GjqtErUM5JSC/61G7EIy1mcJK9OE9ZZ1tvqlwJxNw==,iv:kECui4YKVP2T2soTkgRhUEzLLZ4ugBuaX87HOzXH0yo=,tag:e/fYGh+bnut1++pT1Pd8nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdDYzTnRYWDY2TmJLcnJy
            QzAyWHRQd0U5VEtuU0ltSm1PbW9aZERXUFFJCnM1MDVzRHgwcXBPak90MjFFMWo3
            eTl2ajFRSVRHQU5Yd3JUTm1hd1ZKbE0KLS0tICtTZDBWN2pzQ3R0TEdrMyswWnVT
            aHRtNkJVaWhldEtJYWhSWHBXREhWQjQKeBEPvA9FLgWtDBQQvK2E+XdoSlGW+v7X
            FwfU0Qaej2HpfZscApegnl362kpGqQbIXfgRpGZ+CwmjhYnE7JdRng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-20T13:18:06Z"
    mac: ENC[AES256_GCM,data:MzQvmGDCGBIKGXGJ/s9/7Ho0tksJN+MB9V8e7hDq7QIE7GUv4aSPArDBrXmjVQoW9CcNOWXbhdciN6kEprICsSjKDOG82/F8PSBQS4zQ8bY/rvBNpbGxzFOW/a6Wvaqw4o56sHq0VIKfGiV4cEP2AqcZCxdkai7HyO1bCuNrE1M=,iv:+I1h8UABcs+SqQI3zcrgMuvWiWPjPBM+/PsjWyb/pHo=,tag:WjIuykC3Y+vwb2vTrYM5SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
