apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: media
stringData:
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:JATfyN/6aYfOaF0nSvfizfoH223VAgYzoRfU4g==,iv:JgYzwpdhHWswJqGxP1t2TiJ05WqGbFlHn6D0A1iqKsw=,tag:9aMyQn6YFhwZxj9NyXfRRQ==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:NExReA==,iv:jo/UqjmvIuq/ecOBnEqnhxhkAl3AXTfUqFppm/8SNf8=,tag:g0qDM2gJzldfFb36OxAUFw==,type:int]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:M+FrDHKq1QbLMxGiPov2U6jhcrsfOEIgvp6miLgwid8bIx151jbh0OJdxBE=,iv:V41mS0mq3MkpSt69AqUS+rIrV4nYNQt03v6jcMJpPNY=,tag:hCeoi+f1HdOWpbYsKd8ofw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:pNGeZDVBUw/BS856aEo+18kPplO+H79DODZyn5FGcLH/wx3BjH3GZ3WzFwg=,iv:7CFO0TBnBQdjlfmuv5lvtZwk7itOB+keu6HlWSxLzrs=,tag:qGD13uGyy4I7Gqf/7yvtqg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:+sQ/pX9MHSoQdnxanTkT29k=,iv:OORqOx583cFo+uUXCyiANgm4LnSqDm5uUKdwqY7nTnQ=,tag:iuFN7z0QjWec8/wyanb6ZQ==,type:str]
    DNS_ADDRESS: ENC[AES256_GCM,data:mtEQCGzOT+qYdcvYQ0j72ucvMKML9GqY13fq,iv:tPd2fhawTPZu2fU0k8t8yzauE4aox5tgUkku/RMQ30c=,tag:9di/e92PBVSCLCzl1kM0Vg==,type:str]
    WIREGUARD_ALLOWED_IPS: ENC[AES256_GCM,data:WskAfAvOndoJ,iv:xxMgYO84ga6uLi3eF4Ru94k6qcHcvDbFlAlPCX7Vnq8=,tag:7D+FEORyfkxSmOc0LxrWGA==,type:str]
    categories.json: ENC[AES256_GCM,data:ljEbM2W0J5adMTRUTwYJB+gpAKsocDt5y65l85Pr/+iKNPnvqTL2CG6D8Ucs4wr+i2m3ngqr40gfnxPo0Y4PK9BLZZnTtBj6JtdcpaBb+lXsJPLDU/OzwUAee593z1Wr2knnNbMYbh2SRsxU/j80TJLHACjVEpoW7xta25Sn5s2xCYs+kPTeHS7oMStb5p5snW1gMEVgR73Wt/y7Ed0opzwPkLRgIM7T4yfbUiNvL7tWAZV1S49mATOi1RoDZsDOraD3bofTm+tOVBxhLC/iDEiv5uqMB/5pZlCq7F5S2m9ZWfoAeeTL7ud0717z35/gVFF+Ara5i7mFce9UZaQeJ6I/GLDM9GLLHVdkDr/RnJ/btCDJmUnjRtFLtKgdbtaPiaiKoCcSma+4suZsKEgIvqfSHodhrv1ek7G1fAaQ6FUa3tJvqa4EMdDWBqkTbD2DCftGPQX/HsJXTjR2WzwEBsnx/oZkcPunMU2Dmcwi+faEKip7MA==,iv:IlWl0kspyjW0d1teTSvQkPUkGGYrM0vCJPVEJ79kBCU=,tag:svF1pfGpMpg1Jys0GEoWXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaFRLMmo1SlF4ajJ2UHdp
            NWsyQ0NhNCsrT25CMkxEQ25scHg5eGJTYkFNCmxJekxEUjNPQ2xNTlNWQlZhb0Fa
            QUZLS2ZvSUtHK1lhYXdyZFFjSmwwcTAKLS0tIFptNGlkN0FDN3BSbWFpditVby82
            L2xqWTNNQ01aMTc4RlovVVY2eFNUU2cKAirs169WQ//LcCT+hpkE/gMW+3onVzGN
            usLPFQJdF8XHTP86UalMcaEgCjGTVTSd9OgOR+UOWqfdJTDvksnYig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-20T12:54:02Z"
    mac: ENC[AES256_GCM,data:2LJZoJUT1SKREt+K3mD5TYb841K2kppym2pyFMvH9V3WyQT5F2lb/HEyu2FR/145deaYp0vEZEjZFPYjyDH2cGJKx5PEjBiQTuyCwcZxdpScpXK0owUGbYAA8Gg0dr+PkzUwGtJVpsdyiQv/gZdO0PebWtWk0FgHbefRGLOtPMg=,iv:Jo4xEVQtELychGJdVnlRJUjNOpalxkWzU4GStX3GTpc=,tag:l+Dj+5JdzpYhR+QPTaP+Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
