apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:OVUlKNSfdh5ZNMaXtupClREV2duSbUxAMjUVr06cg3Q=,iv:j2pzZov/GpEb0nO3lofi5AQBPjHw4r0l66t3R0UpGC4=,tag:TNpAIfYou5da0DlTcRaQog==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:mFwcfcjOg8/Cb8bOCQuc+N5Gu7SJcIcMnNC1bgNupmY=,iv:NfxrJlTSsmQnsCCH2sd5bShjmgKODUqqZXh2CnqDE+0=,tag:oot/UQC2wQzBLxTEgDcMfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mge8uraz65urs2222kpjqyfn6rkfgm90n7mqsd43dpclsc69nglqem4d5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV1lGUU16SGZSVnY3anFG
            S0R2R3RXZjdwbHBNQysrWHh2aWNra1lqWUNnCkdLb1JmRElQdGs0RGFTTXdVd3ln
            NWlvZmx2NldKZVVHZmdpTk5MaW00T3MKLS0tIE40N1RjZnN4QVUvOFZqdWttTUZr
            emVMZTY2eXVmanpUV2ZSUTNkTGxrVzQKPMbMIOC03NeyVrq5iWMa0WY/Z/fNrup9
            jUBpczPlf0hTAbXwHzN5hxtz4+jBAg/471XOYf1IcfmdBDERLAT2Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-05T14:43:02Z"
    mac: ENC[AES256_GCM,data:59ZjAXFYY868gqmeGVEL+CvVc8qAPZxUdo4/OZgqpbU4r/Ta58fbPmVrOKB+PXbLzd0vypJW5fLM5H5euDfy84S910vB1kJDORpsasaZ/OYfdLNWs8JPLS+xHEYIHSd2HxJ9uWYdc6UIXDaNPAgdhyAjbAlXcymXH08RvnzX2Ws=,iv:GM3kpXQod64YmaACp7vTGx2jd3qNokIQwE5HHWxHnjw=,tag:kEVhGdGlA8qUmVQXP6KJMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
