apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: storage
stringData:
    GF_DATABASE_NAME: grafana
    GF_DATABASE_HOST: postgres16-rw.database.svc.cluster.local
    GF_DATABASE_USER: grafana
    GF_DATABASE_PASSWORD: WtDcuN5VzW3mdtXxtipuKdDAqHi8hpxu
    GF_DATABASE_SSL_MODE: disable
    GF_DATABASE_TYPE: postgres
    INIT_POSTGRES_DBNAME: grafana
    INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
    INIT_POSTGRES_USER: grafana
    INIT_POSTGRES_PASS: WtDcuN5VzW3mdtXxtipuKdDAqHi8hpxu
    INIT_POSTGRES_SUPER_PASS: VkSRkWRPYVrQSho5ZQzurnJHYxApCzKF
    adminUser: admin
    adminPass: nZ8LpZ7NzKFWLSbrtjugitHoipirzM
