apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: storage
stringData:
    GF_DATABASE_NAME: ENC[AES256_GCM,data:AYuvAkSwHQ==,iv:1YeYJm31BPw2hSePfltD9FAmbhm40zJgY8uHTX9q9uU=,tag:NKbV5Mcwzjd1HWRrVISnoA==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:L5JJZGmaOpUhgfpM1Zxrn+SJAS2CAU+RoLL7zQahl90cTYjAcwq/bg==,iv:DE85StfJ4JqJjo0XsTSWA1y2BbwffZVHd3LxWkEFjMU=,tag:wyqOq/U9JAxS+6TUqm7Uog==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:AZVCsIh39w==,iv:rfLJ11MUqu8lQPeuxJFvYAqf79qv2MaF0QcZBqvoCJI=,tag:gTe7tguLe3jqIpzZ8lGFGg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:1FOpOYfLga36Zp+rIJZ3Iq/v/kxLcOcQsgpjJYgC2Uw=,iv:nicjDoGhDpHRvaGjTihL6FM+ZCmKvXyfz5xiDAdL4Wo=,tag:q19gbrh1HQSnbMJq7VaPxw==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:JTnjY8ttUQ==,iv:m51B/5nkfoHGvw9LxgcqvSrG7WeKeorjWeAT/91IT0A=,tag:2JwF1EfaDePqJgJBzgo2Ig==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:9fIGB4nfIkY=,iv:GAKMoK7/0ePb4t64CiljSa9xIwpsjg4k0NH54lt/GOQ=,tag:NxbF8WzHqAeGygdaVAAYLQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:CPq4HZCMBA==,iv:Lx8oesFC4TNlehTyLZ4na4R5dM32O8bKs1hCUK4d8Ok=,tag:6BG2dW4/cqu7Y0Et2+7E6Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:9gpjojejP9qnGfOXGmSlTHL5pyhbRsq2s4rlNt4PrxicgWONcN/B9w==,iv:oolxRKZOWjYlbp+wB86ESWfbDka9J7OiLAqzYHb8vqM=,tag:wtTUcQa3oAT9e/UZDi5Scw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:/73UyPxTmw==,iv:C3IQe3aAjTBdhAY4e4SFRiRlUVGl4MY0IdkOvclKpd0=,tag:fxbL9o26cZzH2GyRWkjntQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:+rKLVwhgNsyPCFvusyO8DEkKvmpTubwJ4KV6/5dBEZo=,iv:m/8Of82tm3vqv5YANHjH+bjSmHdIaEQ6wyUKJaKo1co=,tag:z5qWYgDqmv2K/TA6CvLgsg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:UcbXORyuAcJIyQqxpVA8CVTQ4/rHnDxuDOtyDjDEwdk=,iv:ggFPW17zqN82BVv+FfwFaoy7N2pyz2pyFsCkR4FTyTU=,tag:NwiLs4dc9lIayGJsjZbqeg==,type:str]
    adminUser: ENC[AES256_GCM,data:UZMLekU=,iv:eTIxRhSsdE09oJO5vSwiBMg/6CStWA2K03+tMtGsPGE=,tag:GOYaje0rgPkBdjJHLk7sRQ==,type:str]
    adminPass: ENC[AES256_GCM,data:6kO2xaWTYfJ444I91waZrNw9NEceBszlBJb8Eh/M,iv:BbMzjkSBIjHTRRjeCrV2UVqP/oTI2Or+1am/3PLsnmY=,tag:HVtai0PUj4dQ4M9iw6VWgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0REMxRytBcWwxUm5KWVM2
            bzJtYm9vZkJhcWk2WXJwa0psNVhhOE43MGdrCjUwRTB5UjhESjAzVFlsOGY5UTM2
            SWJlb1FKNnRkeEkxM3poYWIrK3FPN0UKLS0tIEdlT05JQlk1SCs3cDd6M20vZEtn
            c0ZKODBGSFRCcklmU3JMWVVCV1p3OTQKp5QZbAg5wKCqdOwFFHmJbVOJ5kUf8Ox0
            L4AAJsnoh4RHVW6udKGVJp4GELHTN0KkbgF1G33SqCD1zp3mnJlLag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T06:08:40Z"
    mac: ENC[AES256_GCM,data:sI/gc70ZBkugFbpDpVDCXOKWar3Paxwv/8w4qs54E7sTFfDEHdt1jD0l1+VPjqpmybwzOOv7/EhY+buUsv4b8SBBAA2xl8nQNxzJAcTvbwLg3n2yPR/hUyrMtvU5cthTsttvEXC4YeHdyYtmSxhQPXoMcOCk8CeQB/f1VlwABjU=,iv:CO823tcsC0uEseu5Hc0XZMocxy6apMIgLsnhNpSSRa8=,tag:HaxXWp9oPM4rwqQmquSY+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
