---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ./sonarr-secret.sops.yaml
  - ../../../../templates/gatus/internal
configMapGenerator:
  - name: sonarr-pushover-notify
    files:
      - pushover-notify.sh=./resources/pushover-notify.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
