apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:wrvKo6WbHm2sHX1rWtNbNbQZWUovjg==,iv:zpHbdVPX9vMKYSy+z46Nkl+Emkaa7qFgqhnNlFfOM9c=,tag:mukV4vVX+YFe5t4uS2pacw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:+scPPFU0Kb/UtLlslK6m12d6fmyyao3r861cmcuGUM3vrFCDGbhIJQ==,iv:6CoYzyWw0UMgwtvOyD55M7ebRfTT/k8t7IzphwtbLcQ=,tag:h4HRzORWeAGKGXVTVrm//Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:GBlDCgPJ,iv:zCiaVo1pBwhCDAUkKLANwN6AMILxx10EsI2Nkf1MFmo=,tag:oo7PP5KilyfvLxLCxRbhyA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:c2ZgUrG+DvNK+BwVGBUcsqZz3J7CDxWYyGkB55Iq77A=,iv:Ep9/TZEajhJDopWmAUZSTodeGiFI6H9lnWmMPy+zYQA=,tag:cFYhQsKMZStrPcZpNHHUyA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:nuwb0JL+Qf3K+tABsYqyeI5UXzNhyZQQT1Hdhrm3xJo=,iv:jCJ1hfm2hXwiYGoLVLx0jUTPqAjKZgYD1f2BZMtleEE=,tag:0HcO80Ly2U0rr6zJELEAvg==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:ksywnvkyAs5Hi6BnKl6UnZ/jCE+BgBn6BGSJEZiYk9iX4x+/+a8kCg==,iv:9KiMjKQXByBox8VEYBwdWt3KodvnJc+q83W3f2GfUq0=,tag:TKCQUmXphw2ADgAhc056XA==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:t88jlQ==,iv:kolz4u3QdXHiRsvYXohtP0ttN3nP5tLShNfKdMhZgMw=,tag:D/DmuP6+ntaaoTXkrWokRw==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:lphkAQ7Y,iv:PdSH0mdLsr0S4taFCFE5q0VKiNv29K2oImt2Hdi/rCE=,tag:SdNte9zhRNos1pWjV9ggow==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:pHLrPDGkpj0jGOdzx5AsB0VV2yyVpx+X4o/wF9Cbk18=,iv:F7yo3IVK2otifBmKw7JOtDrYaEG6BJ2sigVh3lsG85M=,tag:d38AsfupY5iZxpQGIgPqZQ==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:f6BNJsE11qGyTy8=,iv:6EOrG7d05Jx4Bj9EX6rmKzjj2yurreg8AvRBlFdWCOQ=,tag:H3gefZV9L9xOfOORXxJxTQ==,type:str]
    SONARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:b9E+wrfYgzvOVw==,iv:/OhqHLodJlmJNATvFI5rR6rGq6cIfDXMMulbvOyvNMs=,tag:/UHMseAFRmQnzjAyvi/1Wg==,type:str]
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:vJK73D09CLxzxbp2PgpSrhP/xQmQFVoULao7zGDCmqo=,iv:l09/A0H7Ukuoo59DG22AnvOvynC/ShjExgEtxcMd45M=,tag:YTj2aegD5pM1U61JoBSRkw==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:ldkDKdLTdogvXiQv5/Yz42KbTNZYcifd+ilk2CEH,iv:ulptM36+m3c3Uj764eFoFvP0e7mPvW5I1tNL9Ak54fE=,tag:cIwxslVmO4s60bqA9XgSAQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:QFDq4aAPa3Uba64UmCI6j+4tCrND4lepi3n6rDl8,iv:2hoh8E2cLQLnRpf9S94ktbY5BWlWIRkF+oKONnIG5dk=,tag:X5FKg05BuF+1VwL3sQBg7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbW10LzNFbE01YVdHb2Ir
            SDVBV1o3MW9kejBHWndhU0tLWFVyMGdYWERnClkzU1dBWHNkSUdzWmVlSDdNcHFQ
            MXZxY2ZqbkZSZVZwZ3BZeGhpWHQwNTAKLS0tIHVVa0FBYU5KUExocGhoSnhJaFV5
            NXdJZnZpejN4WlVpU0w0V3RUU2p0cWsKBfQrd5y11mLQxEbjtX51Gt3GrzFyDEts
            9WjU2Zxlo2GqoTwh5gyoJKHH6yvhNg6yajTXuv1I3Gknu5ZCcochMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T21:59:27Z"
    mac: ENC[AES256_GCM,data:Ytduv+NkV0AzfUDG6DNxzOYSZWcr+cugkKOKesrymRVREL/v4zBGZ0oaikkFLBnEilcXD/Rv8v3iz92qymYcAisZ0Q/gFMyCkborVrbr+kgOijSbfzdbprst/CRRuKZ0IBQDd7NJ5g3gjjDQKo6WcNrFCKpiuX+H1cza/PfzOVI=,iv:VeM+QdEB1pArOYo9hojJKXLBjAGmddG60gqrdvueb2w=,tag:isERb6tR7hO88JIKXW2JTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
