apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:oQjsGCjswRl5a9NWUl2vh4MhQATLfh/mbgPPrzUdVBwBQ6uW3jDdnA==,iv:ObFS1m+Qt+fdvLdO3QBOB7n9BPF933hdC83Nb/p8kGw=,tag:96wXRX4DNsFcg9haDPHxIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwakVLckl3ZGZiV2NKS3Bm
            S0dGTTE3WjEzUk9DUHNlbFI3T2hDZXhmMGwwCjRFaGdFbTlXNklCaldnTlpDUFpB
            Qmhqc01iYjhGd1FwbVVwbnJsaXJvRnMKLS0tIGlCeC9iUDQyYlZHSGx0Z2RWdVV3
            ZmZ1K0hsTElXUlk5WWoyVDRPU0tIODAK6l/QxG8rybW6sf8t1V7zCXKQ+JZ6Oqrk
            0rMYqO4bg7W8O94PFOadlqyueqfsPGLMC7WcLJX7gMRTUQE74rZv+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T11:53:42Z"
    mac: ENC[AES256_GCM,data:2+AsvbmZtxSSf5IE7v67kbLg8LGth8ZFxp4IzGBNGfR0WjFAFmf++xGC5LJz4jwtTquvlEWW9QFhkZ5H6vNSsA0OetTE97PlNbv+OpHKBbyVmUD09KqFsqtfwFLeLjq1uipER7Yfp0b5v6b9qhr2NP4bY1hwd0bI1NmBP4C+n94=,iv:scAoTcIu3vQhQWo0kH2JgciI6jkGEhHWrNuPXuA/UR4=,tag:dQ2QWBOv+Gi1e7rjgO9DYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
