apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
    namespace: monitoring
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:Od59wtj1RWKN3YXBSkLUWQRByiSxDzW5JRmeIOuW,iv:OOTauidPBhRE8+bSvuij/b+sGVQ+0auRSywgfoZxQWQ=,tag:YfFiZKHBO3Vv3RLLdqazcQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:vXPVmcGiGaiZRcTA9V451CGAzYhMXzPsmUXnnhio,iv:ul0c5qfP+gxlQwTAmfOtFKby28JIC5ChNNINXMVaR+w=,tag:tcge10iXHqdyeCRD1qFC+w==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:8bbzyXM=,iv:2bUV+b+gxICTR/16I3YpcAK7bLi4kf0I2PUSuslgUYE=,tag:k4zek/ho5lCc+D/tdwW8Gw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cwQAFIWKCzD+EElO5CVQdipT67XOOhGd+XnHvF5QsGUEvfyeLOpadg==,iv:CEZguB0YchqInnBzMoB5X0JWiM6SAFQHEPqD6AZOTvE=,tag:8e2bxjG1cxupbNaaqZEMbQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:a/6ysP4=,iv:+dfmj1r0KKXZKnm+V15AkO3Etn0128NubbDSdKs0Af8=,tag:Z7Rc9gvrxpY1rky2OSO1Ng==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:2N7qTT7Tf6Y72PB+oCeb0EX1dTDytxRdlFNy7uEV9l4=,iv:WoGm8D2au5pA9SjQxfgBwsxKSvUnOZlJSpnpPrswRRE=,tag:GKi/wsChCbxprcojiXDfAg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:09IpzwDvk1XMUudzb3P5t8XmtU441H8ziXVtHMXq3q0=,iv:Pr2n/ki8+hvyStg9tlma11PFJoNyacjQ4Op+U3nZDlw=,tag:6Jf30eisAWjATEKpGzyBhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN08xMWJtZmJvZGxsOUo2
            QXByNVIzV2ZiNzNFbEd0WG9LZjJjVmE5QzFRCnN1WU5zc3VucW9teWhEQ2ZlMlN1
            OW9pbzJKcFV5RGJzdDYyZUxuSXcyTmMKLS0tIG5LWVRQQWVLUmdBeWNLZEN2Wkhl
            RVMyTFJXN3JmVEs3K0ZrckFZamRPRE0K9Ii+rBodjxQvk/sUU4rH2tx7fqQaSUkR
            2ImeRsAqvIYW/VeOTgTS6HBgPFVf/sP0pUMJe84Rq9KAVxiAlciYYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T22:18:42Z"
    mac: ENC[AES256_GCM,data:fXX92kM9QknKXiZaK9WOllxvLCw07AKs9YN//dQrBAMchF/+HC1T53QRFNNT2UQ5eX6z6TsZVfXhsHx2sQM1y96SJP0nV9AiHnnIAVIFdNsnSMT5Ejj41iq8+0VRtolQGRdePxgr8urD3zJc/Z6uX6cn37UX6AWtf3h49kRmEdI=,iv:TJCjL3me3UbGkMQIQXSzMEiFBLo6DM7lze9+ooWaopA=,tag:JYweFoTLKEJd+a0Sl/xEOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
