apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
    namespace: monitoring
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:DS7I7/r0H+KqNVJlo+1Td9WEX4O/ao+nNSIbpxSK,iv:EPJOFBsZIKksFlMREOnp9F21QnnTN93CF3P2Jc9JnGU=,tag:NzZJ/MQg+ltnPEeuko5iAg==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:d5bbYGWZDmto4//3GT2VAxWmEX+d+0BgZZTFq8BX,iv:/HrstFxDcNwDgYQTvlZwevFuNgpfZgGe5ivfclRSRTU=,tag:YkzweCec2yoxKcijgoHp6w==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:XHuQ9E8=,iv:MGEUMCsX9hArUwCKbugjpCA9Y29PYqvgtKHDXq4XI9c=,tag:AeL/hIefhnlYI+W8pw7l+Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:39fr0BE9zazd2z/zv88QKDHD3LQO1W4rEgkE7kAiv4rC4wzyo5OaqA==,iv:xVtk5c0TWrB0POZboEA3qPr27NQuWtbMHnVchiWvL7w=,tag:y8i3YBS+ovRavYLy9S+ESA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:RDVFlRs=,iv:VrcQl4OVqCq5VzwLjHKHIq9Ii92dx7ZegVo2JBMybmI=,tag:beLdqmVfVt+AMkTQSrxCsA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:xdl7OM6ECbD/ueZ9mqcRFjvlBZGV+RkF9bzPbUGAZBY=,iv:NO4tBe7b0Jzp6llvQJIGBJThdCfb+esJFd/B3F08jMA=,tag:+cwff7Ag9w5mHBhQObFlQQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:I0y0Lnyomf9XFsYMmFBxKq6i7aENwIH8ROkZLgsIRCw=,iv:MbuQXDYaGjNfSXQ8B0Z+NfBlp5q9RZ0hN4vlHj9DkhU=,tag:gTNsr02StSpwcMP1OftEcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13zmtdnufj87wrwe773n0uesm8nv36xjxkm77nlr0u4kd66lwrs3s6hf7qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZFpoeXdUc21hTTVzbzRC
            a1hjYjVPc2Y3RFZQZjFWRUdDbXNpS1RQM1RNCjY4ZEZDeU5XS2VHU0twRlNRN25U
            QXljK1lEdmIwZWptY2xyWC9TYloxZG8KLS0tIHpwK3BqWnhHRGFIR2R0allOYkVo
            cTU1MktnZ3R2OHEzUFdtVVFnUTM3em8KMcjnxE2tFwmJcEMQWcS8I7VeNv98w2Ze
            QHjEdijZ34RR3cLi/eADpaVsju9Wu2ok/uXeCL1+6F3IdpqDu8xqEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-06T17:02:27Z"
    mac: ENC[AES256_GCM,data:tzUpDoGXNqhEzd4aeTK4E7J/RnAIJLLDaYgGeHdas52LiDZ4raELuczMLU9AfKi6B9zuJHFnoMZrOmcbHoD7m/SeS1f+IMAlIrHB6JWzS6yuT2QHjoitaZ1NylOHOybFvrnvALNm/TuVVvqWhBKXA5HSX1wraYO0K2PaIeybfcs=,iv:RdvQ6ZwYY2C4TA7dOf/MNS8ieuBzciPHinIWnWrZXrg=,tag:V0sTlQUTQp8XIE7u9DsCAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
