---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gatus-secret.sops.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: gatus-config
    files:
      - config.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
