---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - pve.${SECRET_DOMAIN}
        - unifi.${SECRET_DOMAIN}
