apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LyIahFzZmWS7BrZqtsQsybBEivccrazUe+o=,iv:Uj14Fh/ICD30/CX1mINPHilm01dIwgOVidImmtxQYPg=,tag:3z15Eu8+WKoMWhc021RPSA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:SFyfu3LuAcNCNmxlS8ytYg2kYAUUKCW8HJAyqevo6EYOLNzYGgHMSA==,iv:ru+31JHfA6OhxV05kkowuIMtyZIK7SCXZ+XfQh8EvSM=,tag:/sTL2K9BEAwnFywuDLO2Dg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:tXdLsZBWX/U=,iv:AwLxqaGv0Avmx4AItbCb+IuOyuN+4ZY1EdHj6RqcKR8=,tag:rl0N+vQ6uu5wIta0KVmBYQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:caznOxny55Ffw/U/KCU45i4ICLxVww66IS8TgOdqU48=,iv:SgYFQUthft9arHjpNe0Tw52MZbKhPzPmhONerWBpXj4=,tag:ved1AVOojMY7wrrlpFGX8g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3Krwc0fWUFavvlx9TQQ8RJ6gPhLln1bUg/suJFi8qdo=,iv:vTSKqqZNtlHKofQ5XNOQRfgJ1ZW1dc3dJwxX7m9Cb1k=,tag:0CjtXHqbeyTL0C/lDNAY+g==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:aUlTO1UhtHp0Y1OJ4bQ+BDoHHDwkznbc8Rl2fDFhvzID8BfKumxWXg==,iv:/AEcqr/M7LPqvf+cltq3zkBRYm590FaCm5QLKv5cBKk=,tag:acA8rJ7PB5EoZxVYGzRjGA==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:7OW0Ig==,iv:K+rGMPlj1rwGEk9yPVGSJg4D0CAbU4VseEzKIN+SBk0=,tag:SGmGWEYCcTWafvjF7YKtMA==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:vsNf6VsjfJI=,iv:eC5V/YIClRCxQWY8tEzjTCz0NlmC3xXxtfoGuCtrXQg=,tag:dDTT0YfrS5iE9+pN53lpAQ==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:1jZ4mLkkwM84JT4R97eVpWqnWoh9jY5NWXxqqWSN/pY=,iv:HoaHI3+Onyw9r+4UdwEhC6fiOT78F8tF8iLfdJl+1sU=,tag:KG1iHh1JKjYjpKHxhe+grA==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:78yUKb+JcMjKICz/MA==,iv:gmh0Bh50TAqvFlCpYv7mtpBODiPrytdMi+V7dz6bmt0=,tag:07MLSmBbtKodfsq7mfGa8w==,type:str]
    PROWLARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:+A0eGJvN5JT1k6kM,iv:xZx7XUyPd7IcMJRagi42ZTNmdfQ42Jjv9lkXs3vvfno=,tag:iwf5s3Te1lxd49W7cAIGFA==,type:str]
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:rvEWary0ydsaWAhp7yDFXMp5Y3JIBO5WHwu3CRyVt/g=,iv:iV9p/DMdVzBaZbYDQgMud36hQNxYD0IcSe3wiTWe+Xo=,tag:fszlIPqEY6ew6aZNbSw6/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTlNoVE02SmMwclhpYStM
            WmttZWovaTFJYkFuMTE1SUpUaFAySXY0YmxZCkJWcDRvbk5BV0NBa3gxcGR1TG9Z
            ZDVmUk1TdFpwQVhOM0oydzNaandsMlUKLS0tIGl2Rm8wUGlZMXJab3JTelpHY2Uv
            NTA0dVd4UkJvUGZyM3FaYW5nTDBTM1kKzQDw61sHjs+jFLw8SyfYvtaYD4ihji3J
            FpA1L8pzm/gIhTu0V3JviV4wgrddpaZ4ltXmydqTKs62piw57cufLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T21:59:55Z"
    mac: ENC[AES256_GCM,data:ExD9rAKN+cgDVSPW6cxUF7WUUaLWnAxeKCjv0a9m/7uDydCy7Yum0Bk5YfUm7E31j0U02liV0uYWEQIyOXh1bj8OlCIQQQyl0bxNuxLZy/yZBRdIrBlcWIjZF8WZr37Wx/UPEuv0csXVbbsVR91eVkNGSiu9YUtYYzIX4xfqDJM=,iv:u50pN+QXlgGGbAWR3D+4qJBpXh7PPT4fQ4IKg9ePqtQ=,tag:UZMublqhEujozZ+sv5tV0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
