---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
  annotations:
    volume.beta.kubernetes.io/storageClassName: "truenas-ssd-nfs"
spec:
  storageClassName: truenas-ssd-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
