apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: database
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:0Nn0el4Il6aX2bWFcfEiomOT3caf4w==,iv:AX/kdG0lzLxVaaU5TWAs0zAf+EZbf4H9DNX9nDGyxUM=,tag:jKOJ2aRxExQw2Q8jYAH4lg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HF+H6UesgweU1lME0vzMp3Bfu1owsWPBTW/Zbc8RyK3M8/HWGQInZQ==,iv:lqrSaFTqoYoSuVxnNN98xYnKXfT4VrWtszL+yzqdDRg=,tag:xeIKj3WBcvS4xwafyg5A6A==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:bEz7i9IO,iv:u0FiEZH+4MD6x95iIcFMlXEkUWFQFwhy1AQfAiBNYvk=,tag:Rhfy2JWZHrxEUU+UblX5yQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:n8mwge/p4DiORiJ1L9TG54cgPl1XaKVivIFP4y9WWnc=,iv:4ypv4wNpK8KGoa7Zzgw9URDP9yZMEehge2mD/2n19e4=,tag:GaRb4FQwqWfgay5YmCFwvQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:D74ouB1DToAnYRgCFqk0hb0DsBvqBX5N5U2TeWlprlQ=,iv:BerASMVD8OXeeXr71THhZ0XbXaysXXJFUXs70iWULOQ=,tag:RTjXgrwvlypYjeiJag4D8Q==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:yGHaix9hZtPxh104uRtZ8wGptDvIj8JSkJ52oSerjCWBPPltzSaaPw==,iv:ltyY7PaWtFkv8u9gbFTVQYup95A2PSlENtfvfPiF7Nc=,tag:GOH5HSqP4bR8SnqFjwguHA==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:sWLBIA==,iv:U5Y214WSvpoBxv8wAn9hetTyjGI68zZs5/q0rcRNllE=,tag:3r3L8QVqSGcQHIu5yim96Q==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:jcR392jq,iv:kX0bUNBoGdSa+phj1MO2J132xyUy8Owg9J5APML31e4=,tag:21PrRpbsMdiv8Ex6LWoz1A==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:2dLkMDa2J8l+orc5MF1TSD94bO0q/K6bP7h4Q577iuI=,iv:qk6WVEqiLOWcPrM/xOlJkY2/icEjxPDjSZJLgfeMtkA=,tag:cFEfx4GPB4gJ0P6eZSvzyA==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:VHZbALYJF5l0el4=,iv:eo/p8iD4BWYPAIS8YsdrCEDtQBYX9ZXxMPF7dHAPBhY=,tag:V1bxwBQ232GJmu6VtlORfA==,type:str]
    RADARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:bdLeeWiTysJeSw==,iv:tzkT4p1vCHMnki3Wzr/petTUaNysy0BTpBxfvODHknY=,tag:k/X5f+Bh3/AY3ufS+ZXUhA==,type:str]
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:8kiwXuMY2UkK1oDxhXWTrWXdKTsxrrohoby0R4xt3ZI=,iv:8AI/cNrGx3WDUqMxGnhUDZWRJHWiZFl6YtY010Yzhpk=,tag:qBLlQp13zczrugbov1aoUg==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:JDvFDrqx9+rCO2Ldhc56uFcLbxQ3AJ+XaU94/hYc,iv:zRJX6Jxw3ZOdzHQIsPQnT7de9DSC1vo70mFgIk2z6MY=,tag:97wJZdTVQXjsymcfD+/Rxw==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:j2Ay76HWmCqDza9fn5ukrjZbIZwblrqy4G9c8PtQ,iv:/qMLe7GFvJpWZgnslUm+X0rQl0EYjxbKR7KNwhDgOmM=,tag:2ogUNB5AaiJYkhnL8q1NJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0tGb08rVHNENHFaZzJ5
            Wnc1QnlwbnpIcG0zK0h5NFF4V0xjOElUMGpzCk9HZ2lSNmdTbSs0eEozbVJiTk1C
            dEw2VzIzWU9iQXJFaHZ2S25lYkZTK1kKLS0tIFpZVGJlczNyVXJEdndERDNhL085
            V04xaytFU3hxR0ZxRGhmNVVqMVAwMTAKD0GCEv64v/N9KQ+2CrPsalxBIy1uU5Sy
            JtBpbyykPeI170WQaltQ7plPHHcF3yOBgDeQKml4wSBw6WRjfBFwqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T09:02:14Z"
    mac: ENC[AES256_GCM,data:peI69nkmNA9tLijbdbKcA7lc4n49U4dCc9K9MhnwiE4u6ZLPGXlNWysKEyHVSvXsX0ePEUaNFAMiH3M+YMWDKZZ/d2/e5YoG7LSqzH3M+00x04BL3QTAwV3LbxBSTDf+IjvqCER1PaHj0pPsH+f3BNHsDERzOvI0us5lNWrn8io=,iv:IFwFcMfu+cLQyJmdI/kJpno9qLI2+AqrQX+rcC0D8ms=,tag:dFPyQeOSq/KVpyKVkz1xmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
