apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: database
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:e+3PQLbb,iv:uS2TBwnKdFz+IY/59WyhPUl7rGLIaCcGnBHGxfrw9Ds=,tag:go/8I9xn4//qJvo33nMbCQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HF+H6UesgweU1lME0vzMp3Bfu1owsWPBTW/Zbc8RyK3M8/HWGQInZQ==,iv:lqrSaFTqoYoSuVxnNN98xYnKXfT4VrWtszL+yzqdDRg=,tag:xeIKj3WBcvS4xwafyg5A6A==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:bEz7i9IO,iv:u0FiEZH+4MD6x95iIcFMlXEkUWFQFwhy1AQfAiBNYvk=,tag:Rhfy2JWZHrxEUU+UblX5yQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:n8mwge/p4DiORiJ1L9TG54cgPl1XaKVivIFP4y9WWnc=,iv:4ypv4wNpK8KGoa7Zzgw9URDP9yZMEehge2mD/2n19e4=,tag:GaRb4FQwqWfgay5YmCFwvQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:D74ouB1DToAnYRgCFqk0hb0DsBvqBX5N5U2TeWlprlQ=,iv:BerASMVD8OXeeXr71THhZ0XbXaysXXJFUXs70iWULOQ=,tag:RTjXgrwvlypYjeiJag4D8Q==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:yGHaix9hZtPxh104uRtZ8wGptDvIj8JSkJ52oSerjCWBPPltzSaaPw==,iv:ltyY7PaWtFkv8u9gbFTVQYup95A2PSlENtfvfPiF7Nc=,tag:GOH5HSqP4bR8SnqFjwguHA==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:Embbjw==,iv:G+CKo2v7UmP+wWnpUsv4ZpNhqDBMepJDoXp+pCOBuq8=,tag:4s+UoiDL1zna0y1QavX+YA==,type:int]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:jcR392jq,iv:kX0bUNBoGdSa+phj1MO2J132xyUy8Owg9J5APML31e4=,tag:21PrRpbsMdiv8Ex6LWoz1A==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:2dLkMDa2J8l+orc5MF1TSD94bO0q/K6bP7h4Q577iuI=,iv:qk6WVEqiLOWcPrM/xOlJkY2/icEjxPDjSZJLgfeMtkA=,tag:cFEfx4GPB4gJ0P6eZSvzyA==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:dM7AAVra,iv:EiF0Hrai4IgR3+ztGq3XJNfRVs60KqjBzACSze2k3vM=,tag:+Vzdx+1zzdcysdqBs5QHqQ==,type:str]
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:8kiwXuMY2UkK1oDxhXWTrWXdKTsxrrohoby0R4xt3ZI=,iv:8AI/cNrGx3WDUqMxGnhUDZWRJHWiZFl6YtY010Yzhpk=,tag:qBLlQp13zczrugbov1aoUg==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:JDvFDrqx9+rCO2Ldhc56uFcLbxQ3AJ+XaU94/hYc,iv:zRJX6Jxw3ZOdzHQIsPQnT7de9DSC1vo70mFgIk2z6MY=,tag:97wJZdTVQXjsymcfD+/Rxw==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:j2Ay76HWmCqDza9fn5ukrjZbIZwblrqy4G9c8PtQ,iv:/qMLe7GFvJpWZgnslUm+X0rQl0EYjxbKR7KNwhDgOmM=,tag:2ogUNB5AaiJYkhnL8q1NJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0tGb08rVHNENHFaZzJ5
            Wnc1QnlwbnpIcG0zK0h5NFF4V0xjOElUMGpzCk9HZ2lSNmdTbSs0eEozbVJiTk1C
            dEw2VzIzWU9iQXJFaHZ2S25lYkZTK1kKLS0tIFpZVGJlczNyVXJEdndERDNhL085
            V04xaytFU3hxR0ZxRGhmNVVqMVAwMTAKD0GCEv64v/N9KQ+2CrPsalxBIy1uU5Sy
            JtBpbyykPeI170WQaltQ7plPHHcF3yOBgDeQKml4wSBw6WRjfBFwqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-17T14:22:48Z"
    mac: ENC[AES256_GCM,data:FpcUhleIPf3ce/6VgFUBaWaGnyhRicBEvM9bBgaGpLaPPUWWdKQIFGkU5kLe1nSQfghdaAChDn+A7wyJPnTz3zGA5Q5cOEVNdtMrPW8DLRrag+PDlSuoBE1uy78FMZTNXlHfwIG6ubp2z/PHUEKPeEAfTCSt7IOrQlrwjChpim8=,iv:9sBZB7ZCfoTMhS7CcmgBs4HteOZXML5MLqc/5dXg97M=,tag:qWYyIU9lL5Iv34LFIQVbyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
