apiVersion: v1
kind: Secret
metadata:
    name: loki-secret
    namespace: observability
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:7RQvT0dHRBAVAA/RvWHkHLKisgU=,iv:6xy5cfclYcVYF1tK6jZdICO7UdkFcw0/KVfQjXjiGFk=,tag:A0l5pIEsYIE8exdyjBx79g==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:asHeDcue7lrQayBAJxu/OJ8HfDtiNwUVJDkWZzs42kwSWT3WdNT8cw==,iv:xEBYBYmaeAPNHDCS/mNr6DlxeGM/gUPRGrWfB87bqso=,tag:zFJosE/JAzypmaHAlwGWkA==,type:str]
    BUCKET_NAME: ENC[AES256_GCM,data:qgbV6Q==,iv:Y+q5v0x/VxCZDB8rixaqZpppaP4Fwqf+iMa78j9/E3U=,tag:QOmqCSEilTmiEXbkvWhYOg==,type:str]
    BUCKET_ENDPOINT: ENC[AES256_GCM,data:pKG3kav3cObEvKCOnczwIBnCwg==,iv:aQ5H5bwvu86iD6DnCX7PbCQ0yUcWJkHBj/mRN/6FMlA=,tag:RXz4wbtHthlrh2uWYe1dEQ==,type:str]
    BUCKET_REGION: ENC[AES256_GCM,data:OCtkf1J2CsnH/GAbQmQ=,iv:BvABy9NsA5ZdvLWpATMiBp7OIJCDS6yjG3aO+6TS7rk=,tag:eHQfOLeJrMlDgVVA3IEjQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNW96UWJRRUc1bkVIckZv
            SHRLSEt4aC9aeFRDY2p5amgydTVveFpuVHc4ClN0T0NQYm1yT3IzS1U2Mk5qZWtC
            L2w3WWR4RFpDbnJ1V3lwbGZLM2dpeUEKLS0tIGdMblBOc1NHYmJ4aWdBOGpJR015
            YWhid3Z4alg0Y013eU1pZDZzb1B6N3MKCEHna5ElFyRZL1AdB+vRDYQYBycirxdy
            ADcvT9EIoqD1erXH3wrlIeHAQW8oz2zBiLjfMlk3lkfnm/zl1muuKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T10:33:35Z"
    mac: ENC[AES256_GCM,data:dxdP6wTlVKVH+q2G+rD5Dj8ubdThhYFKX2buoa4f1VWdjUrKaiyJyColcdiB4OWxiSSO+vCFy2JyqQHqV8XSPLFPPR9apDTK3XrTT2Vy9qt05JvaRp7no+1Vsp4VRBVoSFbK3opMWE9lTPeC26s5feZILdWlpvYjkuKFXeAtQnc=,iv:IVe2078suzZ8MIuTd9OTM6iJi4i1pvZc+28g6bv1cfo=,tag:gK4Rh8i4Jsc2C509SJuKDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
