apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:+Hac22VG,iv:jRQwIt92SGlQ9GMq7Ej/9oU+Y9Mtt7bU88R6vuKLjb0=,tag:Zx/jumr2AHatMfRJFceGmA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:5uK9Xvi7zsUh1jgGDSnK6GuXzn64gV7DDd3P/Q6Q/jIBHj0jzMDqvA==,iv:7e0UdMPpIOaXK5GamCIbyNPScf+BxsUm2fvP6HnYnvs=,tag:kUPsL57RVHVSkkTzGhsbEA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:FeHY5YAx,iv:Jix2J8FTiowFySziGvgzk4xPBSsUzHFabSU7sMYokD8=,tag:l3i0rSLOA1aDYTvLUqRm6Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:T0MVw64PD3g7NVgL5zkpf9/UZieRHildt8AHzFnDkgM=,iv:6OY2wUlZLtmghmZMUIVc0+NnjsteqZgAnLMx0pMdqjg=,tag:4a8oD9mCrhjpEjcExd9qdA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Ee6NnO6Js8x86DsmOfxuaEqcH1ZHsyzLJ7UJoj4TdXA=,iv:pUPjBc6LwT2iBfrFyFmETsUVMy4Vum4jrN7Z3/JdmPg=,tag:4MwV6AqJiDa4VcKBR3LKjA==,type:str]
    POSTGRES_ENABLED: ENC[AES256_GCM,data:8IxI5w==,iv:NUBEyOnk26EVPd0zH6H0Jh4nI3k4f5UrMtl/ryDVUJw=,tag:AhR+pJtflqURDRjXEy2R1w==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:S7Z4frnoPmgoVDPduEBiPYWwW6zgZcDqojMMib0iy+p6/YiqurMT7g==,iv:ySQBaGSsr2PDdV9LaRMEFZrkqiqszsLBKlO84fu1Occ=,tag:Zhh/nJ1T3OaYb5a72zExMQ==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:ssY7/Q==,iv:IpmltbdPRl7HcjG1O0hRyDJJ6/jCLP3NFIqhfO5otM0=,tag:WczzzuVsgeuQbrAAaxf9Hw==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:6IZZ8QjC,iv:EwWlJKsQ4I37YXEh5p3BDK6fx4rIMtftLjukrM0ZTPc=,tag:tCahrad5d3pNkC8IxCf09g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:qUFmkOjuX5k7EZx6Ubz4vjjIFpyw55xli4KK6h2v3JA=,iv:3XogLiu0898YWMDye6W4XUEzlKi5LnFEbB3lUFQfLQ0=,tag:o1XiTDUP0c67G0kPIOrSWA==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:OOJG5MP+,iv:cMBGP8X7Nkb8xoOVp+Tlwo7yl9bRZo7O0c9l383F/7Q=,tag:vRTwHokrqIFQuCr+IsQ70A==,type:str]
    BAZARR__API_KEY: ENC[AES256_GCM,data:yirTGPGpkobOjM21MKsBbQix8Y7IOqFnceQmWKgndcc=,iv:8tuJQSZKtkxB/4uS9EscBd1dEfRBTQ2bqJ44+SSeXaA=,tag:k9JFZw+wLE14GTXDsL5Kbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mge8uraz65urs2222kpjqyfn6rkfgm90n7mqsd43dpclsc69nglqem4d5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL3FaWXlxNjVOb2ZnUFFh
            UDk5Z2xMMFBrZk8wbXJKY3dKN1RJNFR3WjA4CldTWm5SRDhEaDNLRVJ1K2FBREdY
            b3AvelFYbkFzRzhEV1JmMkIrajZZRncKLS0tIE4zVC8zbHFSbGR0N25wRTk1K3ZO
            VzlLNXJ4bkRQWmdTVk9SYXNlbUNUcG8KW8ygQZAGd9ouVlfRsh058nDdaCPE95l6
            ZQnz7fPE+W1hijp9SF/fbo+DBkYFfBzChb69qYZV9IZBt0EMWaLZwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-04T21:42:18Z"
    mac: ENC[AES256_GCM,data:C2JHaJug5hlXXLdDM+V/FXVuKkxitSTo6fXmp36iNrIx49FFHPKi7Bkmj7c8+NaQsdpLxjCoxfX2KzjEbLhfOe1m0N3C2iRsGnJ83pDhEk8wATAUmz0MM54aWUvWx9mXTx525Cdo8XP5NeiMGd0SJbxHpReUfa7OpxKGVmxUnmo=,iv:CNQSq3wnJporoMGC7yxiF0H3ySgjJCqZjmeSmnbqTMI=,tag:HUoiunlI1jsFLBHzyQPrXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
