apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ImeaCn6Z,iv:2g8lEKUPN4PTmJSiuClgUIzNm8OpVrdmK/MdlztcLXA=,tag:fsO7KASAOrepEwDGRh7vMQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:PRAhpW7OrwRYkfR0yXOfK2kwNIXlZ2J/Vw/zQ/w02L9Ob/bnOkEDTA==,iv:9t3ByRwBGw5KfRs1y6pDq32qJ6bYkjEHIM1EJxkEF6o=,tag:QB8+2Bstbgy9i2qKcH5Lww==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:J3Cs6R0f,iv:hosVMBONQvYPVguG5DvSQcg29L8RZvUdVZpZtSSsCq4=,tag:56RW5sD/BzqgkLvkSlA+rw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:S9tFXy5XRJgYT6s5MrbZiy37fhZNAGjOeOpmRXo/M1o=,iv:8Ot3qq7lffbftOn2I3ACn5BfCukquiE0ntyz3BJg5cE=,tag:TMbi28x/b/seZoUBJOjaJA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/84PHCrvHm7HhskGg7eahylo1WpSUQgoN8oB7BKSG8o=,iv:hB4faXlUX0yIqkepHDb/qph8AFA34NTipPwIE/CUvdA=,tag:phuDwNDuXfGxBO9DAQHaSw==,type:str]
    POSTGRES_ENABLED: ENC[AES256_GCM,data:348Rcw==,iv:+GjikZIqvfUlil3VoXhvJDSp/dTEcZs1LL0lAiKDtGU=,tag:qVBRxA2OwrmHmL4epE83nA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:mbjK2ZrRL+eGv/B+/q8NAHA9QM70aN1P9KTkJ3RiT0p+ywXuUR/dnA==,iv:fq7Gh2ugDnaoL/l/nGZTDXGKojib1bmi7dg6a+sdoqY=,tag:eki+eAbjNMLNKBoY10U+nA==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:ISOT3Q==,iv:mlaNgfYLFt9qP3NCXrjylE5hJjf5hnRz6DA8D5yUp+I=,tag:ieN1e6kDYeU7luRhqWyyyw==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:OljNP1su,iv:CEQJm0oIAY+9iKnPTJNoyGMpiAeMf+VBucWn6VvU50E=,tag:5DK/BdqCBedjyJTZtwBGZA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BGcDv5kPq5/g0Pisywn8K2hRPmw6LLmwkf6nRA0Uz0k=,iv:YyNHJdlNCOna5SlAYOw7Fvodg3xNbKxWBy2hFh3OiGg=,tag:5wXwFGEMnhK/KgdfymjRvg==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:ZQxGhIEP,iv:qNNg0q1UzFU2E27d9/CSvs+PegGEUSXq5mu3FWY3QPs=,tag:nhVKTxxYjJiPR4a/OGr/Aw==,type:str]
    BAZARR__API_KEY: ENC[AES256_GCM,data:FY3zGU2l12aA99FiU0HouKtdACekck2DcFmgYXiPGuM=,iv:+QZv/a1ON+cR2r2qaKI0JKo+Goiyuz31r4M2q8XzkkY=,tag:ukl996m0tAXXM9RzfCNDlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMk54a1kyRkpMQ2JmTFVp
            WGNuV1VXSGVwM0U1NC9OMkp5SldHTFcrdmdzCmNYeGc1ZEZVWGZBTFUvdDR6d2tp
            U0VLNGtBT0RMWlpBdTlLOHdVKzBBTDQKLS0tIHhIM3JXb2x4Y0dtMWNUQ1E0WDNz
            UVVjNHR0Y1hjWUpWSHJUYzFLVkJzNk0KlxJUml+pA01j2hf9laXWNitbp908nyh0
            oxvJnk9n+bX/vmi6MN7H5gKtif+Ey0Mba3FaxC2o14YWO6scwMRXOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T22:00:43Z"
    mac: ENC[AES256_GCM,data:oNtd2ZLkJd7Y/0RxOvBd9IOv57n1dLt1N1Yr+WMDrvUJVxHDni8mCfkT8Ung1S4Sv/QvV3uIfaeab9SeLBX2xjkOmGLeNynIvFQxrHiPeuZlqRn3ZwNb2y/0RmDwqKFOfP3ZCuTqd3sVMDkNQAkmwE5xFWjYgK3lMqmWpecf1Uc=,iv:MZlccPyaw5YnA8TO3NwEw7HpAdP3XPJopkoSw8e00UI=,tag:rtyIxnFYfsiijRnyGiX0lQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
