---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bazarr-secret.sops.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: bazarr-subcleaner
    files:
      - subcleaner.sh=./resources/subcleaner.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
