---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bazarr-secret.sops.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: bazarr-scripts
    files:
      - subcleaner.sh=./resources/subcleaner.sh
generatorOptions:
  disableNameSuffixHash: true
