---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpoller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  values:
    controllers:
      unpoller:
        containers:
          unpoller:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v2.11.2@sha256:73b39c0b3b8fa92aa82a7613d3486253ffbd8c057833b4621402a268159bf2a2
            env:
              TZ: ${TIMEZONE}
              UP_UNIFI_DEFAULT_ROLE: home-kubernetes
              UP_UNIFI_DEFAULT_URL: https://unifi.${SECRET_DOMAIN}
              UP_UNIFI_DEFAULT_VERIFY_SSL: true
              UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:80
              UP_INFLUXDB_DISABLE: true
            envFrom:
              - secretRef:
                  name: unpoller-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # UniFi API only polls at 2m intervals.
            scrapeTimeout: 10s
