apiVersion: v1
kind: Secret
metadata:
    name: unpoller-secret
    namespace: observability
stringData:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:FyypZVsNv3k=,iv:StfavhHnzRO2sFz9xwQSJq4d0WLimMJ0knyxFjSNRYs=,tag:9QW0UyclRdCZHpcqIToizw==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:M5gsIZBQLCCc+GIkrDAYZsi9Se0AjvQqmIt8gOoIf8k=,iv:SS6FGCegZRkKxo1vSKTrz0PsuJ553b5YKKskclEiU6c=,tag:Q7cTNoSrc8nx0JpztH12PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTG8rVUQxdnFCK2VuM1B6
            SEZRRlpLVFQ5S2dBdHVINm53MXN2QmtoaFR3CnpKU0VneTVjY3ZQY1BOWG9DMnYr
            cnVMTXpoM1Uxc3FJTlAvUExPTDI2M1EKLS0tIGNZVlNIYm5TZ0ZxaklXOXpYT3o3
            U0lvMm9NYmwyckd2cEZSSURwUS9GeDgKfzPhtYy+gFO+zTADAihNxrphI0aOYADO
            9KHsB5bwl2YFuoAgiWE9b0X0WVBtWer6861NmNEVfwiDvFlWuS24Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T10:14:40Z"
    mac: ENC[AES256_GCM,data:es67yNjevu9isvQQgERV3Z4LbtL700GMs9SdpVlog+hjmNRihGhfRRNnp3XCCCUm08ufvuO4dlXIaC5WHg8s6K/TPwWgMT84MOG5AygvfJo+zrWo8a2urbT4fLNuB/ruDgisiJCZ046uMDoLMVTlcyT60u3G2Tl2C+O4wx5rGaY=,iv:rmFOAFV3+u1zPGgJP1ytIHjSPMMVlN2m0ihigaft1AE=,tag:EOqbIsL97RdS4HZroDTkPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
