---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Stockholm"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "192.168.20.0/24"
  K3S_1_IP: "192.168.20.21"
  K3S_2_IP: "192.168.20.22"
  K3S_3_IP: "192.168.20.23"
  K3S_4_IP: "192.168.20.24"
  K3S_5_IP: "192.168.20.25"
  SVC_INGRESS_IP_INTERNAL: "192.168.20.40"
  SVC_INGRESS_IP_EXTERNAL: "192.168.20.45"
