apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Eufv4Jqrlt2q5KCa,iv:JWAENcmzu3OsPy1Jin2AjFoqWepYkZc/cD/rOjiccuU=,tag:FwDK3VsDy1yr3zO1na/+Ew==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:2e7Dz2S3hkF8hL41oQ==,iv:8shmLAOM/gabWZD7GTOGYTXbm4JqLm/u1qbBevPq680=,tag:L9vd/YHeZb1sEEAmfzOp/Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:j3W5lMyqYGS0gaeivbFNq1xJP5pR7ck4hVhQGJ2fwqX+/4Ih,iv:5/lsOrmnAVB93F2ni4u/6PKuKQ6xNmElY0ZgzxcLSwM=,tag:ipXmzEscIpOQautYkEt85w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mge8uraz65urs2222kpjqyfn6rkfgm90n7mqsd43dpclsc69nglqem4d5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZG1JazlaTjJlcS9hblZ6
            RStUc2hjcCsvdEVkWWEvb2FOa2t0T0VWTDNNCndjaWxxTmRQMGFWZFNUbkdWenQx
            M0h5UUhtNTZOZlhRQXkra3MrVWFWaG8KLS0tIC9iOXBNdFVNSHRwNFo5UmR3eGpj
            VW1tOXdRbHhEWnJRS0N1V3QxQ2w4ZGsKPFq2TINXclrp7j8ibwoyxtsxvOViO+Od
            3UqI4uTU+muoX8bk9LwE2pEb7xpppmiTdR3uqmuzoe+uQihV//W7ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-25T20:57:34Z"
    mac: ENC[AES256_GCM,data:l/zUriChdPcu0fF9IfESLWWOB/r1DS47lQ23btDebHDA3P3ECIoAu5Dgi5/+EiUXZ7JzorA+aKLtmV7cojOURy0maw7heX1ep0sOYZnMUc43xSEFX3P8/LBIaKzqu5EvoSAQoAVO2H5AU6tdqgvKVZXJmGopmMefv8Toylz+XJk=,iv:Eo4oSD0bu0GmoYpbFYprISisuzZgPLPXmic4hpQOk44=,tag:8Vv3W+kK3UGTg0UZPLoVTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
