apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:8e9VJOVmLPd+P+D7LwyTwsDwkMsytAOUlut+PgiTXp4C9xXnhN/lpIF+sLR4SefBa1Rfc5GuL0gUusApsaraaX2szBbM70QNP7Z5wVYE6ZlMfXazmVzI0PrRSfx1bg==,iv:CVkVD1tpeAzQ6p2v5BSHKSbvoFezZBjyE9pYHIKuIVM=,tag:B7SzXPGf0ga6E9lHKvs3Pg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:lU/Cu3ttHrqs5vtG,iv:khf5kupYWwOGthnED0Ft/pRArz/7H6/G0wNRRGBOj9c=,tag:SeAKZfml1kzJrLUTPqSIuQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Tjbsa8T9CURAXjL3Ng==,iv:0X3yq/bN9PaQoRLCjmA+8sm+zGUlMS5lDqw+W0jeCQk=,tag:TUxj3nnIlvJzhnLfvIh89Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bXbG4t85HcHnY41tfOGbcIOhuxYF9QTYuWBHsmt73KND7vc2,iv:GAHHmBo72EarJQegRrev2R+eT+5KQNAiyUnbj+K24GA=,tag:wEB3g0QGEcox49hKNCZkmw==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:WFL4TwIpWBWNlA==,iv:s0Ybo2/H3z8rfp9cjYVCG4mvg/U2JPjOIjTQQ+IOD/s=,tag:O0kzDpBbszfyyV4YEZEO/Q==,type:str]
    TRUENAS_API_KEY_K3S: ENC[AES256_GCM,data:mL46FlYXXoppE1so9r9QXJBAOg80GtzDoYEsN4SZEnj7hRPDyy9Ec0uUWd+hI0gmF5UXEM+LQ+AxdUPj87G1Dv6P,iv:y+3IwoU9sfoAuLw7VcuUo7tLHn5vmG/QDryjS9B6CO0=,tag:j3edDXVtoP43EHDe4zURCg==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:P0BZkTm8s1pt9nMIUXRRnsjT7/4=,iv:ks4gI/WllHC/bj0MRf3/d6AT5Bt0em7HE3iUQrd0O3Y=,tag:w112KDtUqs+sqb7/navy5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQW80NnFvM0lFMGFLbWM5
            NGptZVRUQ1dwaEpiaTU0MmF0dzRDT1g1NkhRCk1EaFR1czl2ajR6d2J3NG4ydnI1
            dDNRczdJZ0pLMGZyNnBQbGVVYjQ0YTgKLS0tIDBOZ3c0VEUzWXlEUFQwVXhDN1V0
            U2krL0VHUmFwNU1BRGlzcGZCdXFCM3cKakiG7zkO0ygCRWEoYyseSh2TU9F3M10O
            PnPl6/97TuX9juNDGrt8wdIdi7HtyCWRoc2iSj/UNBasjFmUzQPUTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T22:01:24Z"
    mac: ENC[AES256_GCM,data:heTX47kchtBAvjwMaq7ytDjtyZGH4H1hMxuKMbFmX5r80R9DsEaXx5oX5GngGmwvvMqQnOfu/h65fLn+SSfAQPnKCr1u9A5jmKoEyEYqGn5ByoNmizuowmWailx8zLcmIQXWPliaS9r1dYw4BGqxPdbRgBZ+1PEbPwbDtzc38tw=,iv:iXrvI97DdNvXGQq6k/ZtAZdEeQ96m9HmhZCTbrO9M0Q=,tag:5pe8UzWXk8u3Yev73AzC7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
