---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pgadmin-secret.sops.yaml
  - ./pvc.yaml
  - ../../../../templates/gatus/internal
configMapGenerator:
  - name: pgadmin-config
    files:
      - servers.json=./resources/servers.json
generatorOptions:
  disableNameSuffixHash: true
