---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pgadmin-secret.sops.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: pgadmin-config
    files:
      - servers.json=./config/servers.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
