apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: database
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:vr2sfoyvl5lGKbdpwA==,iv:SRUnqfARypAxeBpY2HOnRdiWayYQWdMTAvH/C5yMIb4=,tag:N3HVTtCYjpajW0Td1yJa5Q==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:38rQm0+IVdinGCjfcBVbUs11MmNNhcr4Pie1XtoivprCSqLAqFt4erukTixZRQOWqBk=,iv:dwa/pATCWF4U+cFdw8bE1KGtqtQXHcUfCt1LlNCDxa0=,tag:AA87tgnQka1cGwLc14l5/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mge8uraz65urs2222kpjqyfn6rkfgm90n7mqsd43dpclsc69nglqem4d5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOTZVTUJLdkd0TElyQ3Nk
            NERhMXNxbll4YjNXbGVaSHdoaDdpdVVUNlJnCnpOZ2hEYjV3cC9FeDJuU1E5Rkk3
            cTgycXd3S3BnSGlRTnc3QWc5ZVZFeHcKLS0tIGg0RFFqamd0ZTVTRENxM3p1a0hG
            enhnQ0dxdk9hdVptLzFFTTB2NFhVNzQKxHheCxmv7kVwSToBPjkCXVqYh9yKUEbV
            3+vsdqJDRR7RY35MU3hdfco0xdWKZGsi/kPK1phbDtVsKbdrHvLIWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T14:25:54Z"
    mac: ENC[AES256_GCM,data:vFJ8rOkoJLhSesQ+EnfHakCAPhjNQoKGV4KPraO5dz4aWRUBKDnqXKGjfWvD+ae1hVf1nORwXxj7GvuUkA+axTOTZ7qIvr2sT8AeKvXOPrrVpmLT6n5lRSDtbU7b+HWqx9OJ5GP9rRKKrjW3jglX8j6rAPStNd4H6r7LzxmTovk=,iv:+OvY68CfzwDEWxE2N6j7ZtQH8MT70sky+hKdBsPkwfk=,tag:vbf9JVYl0QbBPfAMa//8PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
