apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: database
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:hid163WvT0UesYUR4Q==,iv:RYMzwgAG5B00FdWCmoEMuyaLB8f1vDeZhl+ZZDSJhzM=,tag:OMUtWjRFF5V2lyQbuh4QBA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:/DcgMU1CWHD7tK1yVgR8BXlCD9aPIJcor/UUb1bpDDF71hjtczlSk7+SDHOWFPyhYFA=,iv:UrnMiM5+5T2u2ZiS7A+RhN+aucmMJ2XG5tPZGHZjOpg=,tag:TOO8ImaUUa1O6sLeRXaytQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSGcxQmRMYUdhVmFpdFpP
            TXVRb1Q4VFUwbUMzQkVzaHNkZXdub1hLc1FrCmZuZU1qK3JmRkl2VE1QMk56NUFY
            QlZWb2x0SXRaREhROEk2NTRYVklrTEUKLS0tIFlPbkFQdnpVaDJXMVl4ckVWMmJu
            YTlCaFRJMXZyemFWRjhBVkhNcDlIeE0KAaZtvCL4a0AtNYqa4VAYBJT7Y4gHOqLI
            srOiiloFBhEez2+S0JOjJWkETWvLs9urSPxVeFe8MTMqJbo0RBKTjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T21:52:21Z"
    mac: ENC[AES256_GCM,data:3ax7uiuuSQN5LwgW7IARtNGwKVZXEWTM/VMDP3bzpwUFSXeaIrrCSpIZiNIacwI01OMZVAjBKTch/Oj/JSGj32ltUH/z4JELOdixPt0DWyvem5p73Ix2fIoUDAFk8sJOkyqhoqjg9so0IugNECZG13V38Gc223PMeQyw8Nm3jKU=,iv:s7vNFUtQ3ZSZIjtJbSM3tCx/jNA86L2Ko3J5mqP0+eg=,tag:hKXNjpqzHnLOarY2v/lGug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
