apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: database
stringData:
    PGADMIN_DEFAULT_EMAIL: admin@wyde.se
    PGADMIN_DEFAULT_PASSWORD: VMdHvm4SBXy4fwE4uHevAfkChsB83jYA7FPiSe9mlBphlt0UPu
