apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:IGaE1uxpTRY=,iv:4um97O/FHti2OlXuU9RE5WTD/QhhhqQQ3DbWFcsctQE=,tag:3NqwQvm0hj4i0pEGRmBV1g==,type:str]
    password: ENC[AES256_GCM,data:jhVQd82miuXiOFOS40qK3eyrm5ogJRW2828l3xURl5U=,iv:1H5L2CEnaWFh2/agxT82LSkekbZFVlhKbdYI/94D76A=,tag:y0TRB7dGyS7G7Tb/5ax+mA==,type:str]
    s3-access-key: ENC[AES256_GCM,data:FJpGGcwCgqFZBNwLikMWWdOGp+0=,iv:TByRMqGZe7RR+iR3z+VY/Ms0m70kbSZ7DxEJkFqpRis=,tag:z9vN7QWofq6mBHOZMLjGnA==,type:str]
    s3-secret-key: ENC[AES256_GCM,data:thoAHQ7lLScNvGnT0s56p5zQ3VBQPAw9u2VvX8uGgH3cIX0pENyO+A==,iv:3DgRpN3L1pUuebJcrKHiSLrGTrPYVDFpz5MYvgK0TTI=,tag:1wXn+KLxZ9YyoarkXGN46w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdERBaElDME9FcTcxck5P
            WHBOUjNuTnNXdW1UZld3S2lxUTZYcVEwOWdnCjhrMmxOekZrbmxkMFJkVDZ0dzdH
            ZyszNk1EaUhlTFI4bi9EZWVySWo1eDQKLS0tIGZaSTBIQmJ2ZEc0b1pBdDZ3cGhI
            TFE2YVZYN0FyTnQxZDl6cXIwUUdEUWMKoMuPqmsP1GqfGO8TzKcSYjCHemOUEfLI
            gLdbqi75VemD5kj86yK0uvXQwsL3AMMN/YYhVrRnqGoDxL8+J2pmiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T21:38:25Z"
    mac: ENC[AES256_GCM,data:g/BdfqGoQlYbVcgZYYGuRD7MB/mWJRUEA216v+TILK2ZGNQqVR6q+eFrlbXaFl/G50xsysRKEjOh0JinWOsSdnzfwjb2v4AnyB2H8HkL4K05bqyrHPY0He3y6zOELU+TL4w3Ot/MSf+zj7dy/TRRPMLxpK7VmQ21qMfHluYihPc=,iv:XJnitC3AMEOULRYhxoic2etlHQTNcWcHgz4dZsID/xc=,tag:2tcen7O1QW/8Yp6XAwEJkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
