apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:qFGP3ieARgT7ELh0fBrwlcAjUZ72JnYT1ThwsrEXeSk=,iv:XCTFhKAx7u6MTEsL7zHTMNAIAI9DQ/ykS82ueu+SUMo=,tag:oCpFd06X4QqENJW2RNpo4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWDZELzZTQmk0V3o0bGpW
            SEdaeVdqTTdBN1lkWWRqU0R6R1B3RmdTd2xzCkdEdFFPcGpRK3ZUYWJhMTZOZDVn
            azJHWENRZHBGaHljM2thRm9NSFI2ZjAKLS0tIHVERDFqU2N6VHF5Zm12WmRvdFBW
            L0owb243bjdSVGdDWHpRVmQyZ3NCS1UKDxBG+pWIkF+YaivZcb13Xf1nNqa2kdGe
            otQZN7o3OCe1HHKA3gpctYzKYFTx/EykA1v/KIggdrcfPdIcvp7n5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T11:53:42Z"
    mac: ENC[AES256_GCM,data:sKftP0ONhdPGjSzaL202krbnBbpnrAMkSPWH4B3zzaoH9u7ZkhyHnRU2s88ivMYMCIn1X0Ubw1mhDqZGqjfHhJKk8zJk0GE5xtQZGbGQfk6KnxoqsITnLpqOaaQO+/WO22aYtBbUehlPgWY9GJd0f1pnHaw5zl2S2OTWPfYbnBs=,iv:F/+TGZFc7lBWuUbyNHX98m+yGabCVExUUffpQL2si4A=,tag:eWY9niIp7iXucwGqge/6PQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
