---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter-scrape
spec:
  staticConfigs:
    - targets:
        - pve.${SECRET_DOMAIN}:9100
  metricsPath: /metrics
