apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
    namespace: media
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:20MsrEAxNWxiCQwfBRckoeZFdVSIjg==,iv:MJYLU5tQmEGk+Vh/xVd7SxdPjTyLQZEefMMNTzaHMtw=,tag:uzCHYlaMcFo38DnVTLFdtQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:OaT6TjNekWcHtxg8Sys8nYBdBS3y6YThsvOZx6D8D3m/SZ3mgvQ+TA==,iv:cFmtG3uI63lEEE2f26B1HG0t//ClBgBYZ0WECTKuT+Q=,tag:LhIwsL1uyp+qrqFnnpRRAg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:igF4mNeR,iv:h81QA5aHaqh7/zD8JNRGK0ENNw9UMzLzA1MDqA8PBtE=,tag:pSWLZpl8s3C4dCkS8zIiBg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:f4QVCeLEkPlw077/yXNqw0IB3i6gCmYiGbBza5DgEaU=,iv:StZ07qBZwLllIDnOxMAe7iHMz0CbtK33I5I6ToN2Mfc=,tag:1z7+9TsV+1XDMF3x53Md5Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:zlz57HStWZS0drj2GMOnwLo+sOhY9aFfMIJ9qAnv1PU=,iv:SnFdwnMQjb/6eE0sq9RJgpe+b1IdMxJFEbMb2VIznhs=,tag:MqwMX7av+ZO1m5JJ7dCiKQ==,type:str]
    LIDARR__POSTGRES__HOST: ENC[AES256_GCM,data:ALYq1BfjrYIx8QkNzXgn2c9BNwf+2GHd5yKpzDy1gJbh7jyqF5s3Ng==,iv:VQxf1g6GCbN55rGR3td2WyMB2El7eNbx+SuYzKuVt0E=,tag:HFJyFju/OrZCt+TKSrFOMA==,type:str]
    LIDARR__POSTGRES__PORT: ENC[AES256_GCM,data:5m+ziQ==,iv:IVgWmKOg24hPQxifHOxIt3sKtdMijnbjLpWpbRRk30c=,tag:x9Vby80CRw+w2Gt5Ew90Gg==,type:str]
    LIDARR__POSTGRES__USER: ENC[AES256_GCM,data:lb6kwmS8,iv:5dDOFSHuN2igTuM4w3ukm186TQfZtW65DPXraQv8z5Q=,tag:lUYVeDojELJU60Iv9sU1Ew==,type:str]
    LIDARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:47RdcgR8V3s6iH3DpPfec3m5+t+2NuLBPyq/w+0vkkY=,iv:suKlxFUKeQZueAkIeXWnZpDzRWkikeDd1Goi78ls2CU=,tag:kOKNdLqbeihQDJfnd8OPJw==,type:str]
    LIDARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:/fJhdNb8g9cZ3Jk=,iv:XGUYmH8m4MfOlWIjfLYjkrLmr1SyQNndXxNy21p5odc=,tag:U27OpA61v/yebE95x2fwSQ==,type:str]
    LIDARR__POSTGRES__LOGDB: ENC[AES256_GCM,data:eFKW3RiRJQ19HQ==,iv:5Zl8ar1UqyATiXH5ydsNpGhnJKUEyv0ITa2RZ0GtHAk=,tag:zE8QUlqZP0Z78JtWhSLOaA==,type:str]
    LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:vuREON0JoEAhIl2CLzYfILCxvw8kUPB7LdZGdpwLP2k=,iv:qoQaVkvCdqbdUjdH/rvNCCwHPWvDM1hVunox+JQe0AA=,tag:WgugS5aYEaeA0pVG0eNdsA==,type:str]
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:CjR2GDHy27yD75efjfemVrY7UvD8Yv7i32z0gPn/,iv:XCrrnOfTAD0m2YvM6+fy60gFMBCxZuCqdq/As1+FdXk=,tag:d6K5TX/xY+Ml0jPUNunbcQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:1FFAw9QRMxA85m5OKJX2rK9oMys/sYGw7J1fWhJV,iv:cGCsBTEc5bTomsgQdM2x5/ZPMLbGfRNYZGHfsEwGGY0=,tag:smj9vqb78WKDXAiJ11YRYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RnFwN0sxS0hkUjlUWjRO
            a3VyL0NSbnpEZy91SS9kTmdNZ1hvT242c1VVClJNcHhERlF6TlNmNnJDTFZRSGV1
            SEdqazNtMzRiREF4RGpxTlhkSEVjZU0KLS0tIFRLWmxTcmlXRFB6ZGc2K2dBaHNH
            cVlWa3czaTdQWFBySzFoT3ZRdHNBM1kKn0CWN+wipauaxB0Xow0+oW/uujKHeSIm
            f3yDsXwVU/JxoWMwzelF4NGrbJZZ8axuqp/m/UbR5UORwThACSRuKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T22:33:24Z"
    mac: ENC[AES256_GCM,data:yPN0HCvfwXCxLAilLlLGtQ3C81fpPt/0Y+mw18myiv6wChUcyD8vMHIvQqIIm5Z+LkTu3siAYGf1r5gtZhuXTC9hZCUnQwEqviKsCIFF6Lz395pQeFfCnNizYQPbpWqLzOs8uWnD0sW9S+d+eHRHxiNtOtbSHxOQIOo6QMgr1T0=,iv:H+Ljr7EoQgsqZ92oxNShznmgx5QJVNS171W5v8PkmqQ=,tag:rbCtvmjkVlJx1QzvxzggOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
