apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4dWhV/XBOGPn4tr/93RXRrjG2NB8rYYHabLAE6yGdDLgtSxeXWO15g==,iv:mxF42RYZBmv8mWHlGPEUP49Tohg8+YHa8sQ00shezi8=,tag:w6pGEqbefYcBN06Hkz3Aig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lwq7plulkvt5qek49zd4dukffcjlmh9kk3t9duhyaayvauluspcqucrln6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNamFCcERwUDhjZmprSHRx
            ZjlReEhPTHFrOERWTUxVbWtqSVIxZWROdzFzCmNWOUdoRythVUVmdlo2azBlbVpX
            eitxYzlwa0tFTW1iUFNZbkdwL0Rwb2MKLS0tIElSNlpzaElxSmhyMGdFRnFCVmFx
            NHl2T3BvcnZSVTlHT3JxQjRJRnMzTWMKBQaL/14Tzc+lvql/fxahou/D5lvdKMk9
            OdHTZ9/tVN+dBgzIMLJCyFOZ69tNCE4ftxEa2RQEiBsXpB+pJt2o0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T11:53:42Z"
    mac: ENC[AES256_GCM,data:gjPxlRHafU98hB0nmECVMFa2F5qRBCHyihIqxAVNy9kGGXPY3qD43e8P0GTFRbEnFU3d96/g3BQq9w0IRQACLIFhtDMLtBr49EW+exJYlukS6PibIjuorzPXMQw8FQg6fUl5e99yh8cNRkXXV6/igZwHe14JbAd+9U0lmIV6GNQ=,iv:Zsq5o+CD494KTi9vyZiyhTo3keUdIPyUe85xazySd2g=,tag:Y4CBofqdAdsS9GvbsTL+bQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
