---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
  - ../../../../templates/gatus/internal
configMapGenerator:
  - name: navidrome-config
    files:
      - navidrome.toml=./resources/navidrome.toml
generatorOptions:
  disableNameSuffixHash: true
